// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Kindgi Inc.
//
// Generated by kindgi-codegen-maven-plugin from the Kindgi API's openapi.json; do not edit.
package com.kindgi.client;

import com.kindgi.client.internal.Transport;
import com.kindgi.client.resources.SettingsResource;
import com.kindgi.client.resources.WidgetsResource;

/**
 * Every resource of the Kindgi API, as {@link Kindgi} has them. Generated from the API's operations: the operation id {@code approvals.reviewers.list} is {@code client.approvals().reviewers().list()}.
 */
public abstract sealed class KindgiApi permits Kindgi {
    private final WidgetsResource widgets;

    private final SettingsResource settings;

    KindgiApi(Transport transport) {
        this.widgets = new WidgetsResource(transport);
        this.settings = new SettingsResource(transport);
    }

    /**
     * The {@code widgets} operations.
     *
     * @return the resource
     */
    public WidgetsResource widgets() {
        return widgets;
    }

    /**
     * The {@code settings} operations.
     *
     * @return the resource
     */
    public SettingsResource settings() {
        return settings;
    }
}
