// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Kindgi Inc.
//
// Generated by kindgi-codegen-maven-plugin from the Kindgi API's openapi.json; do not edit.
package com.kindgi.client;

import com.kindgi.client.internal.Transport;
import com.kindgi.client.resources.AsyncSettingsResource;
import com.kindgi.client.resources.AsyncWidgetsResource;

/**
 * Every resource of the Kindgi API, asynchronously, as {@link KindgiAsync} has them. Generated from the API's operations: the operation id {@code approvals.reviewers.list} is {@code client.approvals().reviewers().list()}.
 */
public abstract sealed class KindgiAsyncApi permits KindgiAsync {
    private final AsyncWidgetsResource widgets;

    private final AsyncSettingsResource settings;

    KindgiAsyncApi(Transport transport) {
        this.widgets = new AsyncWidgetsResource(transport);
        this.settings = new AsyncSettingsResource(transport);
    }

    /**
     * The {@code widgets} operations.
     *
     * @return the resource
     */
    public AsyncWidgetsResource widgets() {
        return widgets;
    }

    /**
     * The {@code settings} operations.
     *
     * @return the resource
     */
    public AsyncSettingsResource settings() {
        return settings;
    }
}
