# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2026 Kindgi Inc.

"""Generate `kindgi.client` from the Kindgi API's OpenAPI document.

    uv run python scripts/gen_client.py [--openapi <path>] [--check]

The source is `@kindgi/api/openapi.json` (`packages/api/openapi.json` in this
repository). Two files are written, both generated — never edit them:

- `src/kindgi/client/_models.py`: pydantic v2 models for every component
  schema (datamodel-code-generator). Inline request and response schemas are
  first hoisted into components named after their operation, so every class
  name is stable.
- `src/kindgi/client/_resources.py`: the resource tree, sync and async. An
  operation id `approvals.reviewers.list` becomes
  `client.approvals.reviewers.list(...)`: path parameters positional, query
  and header parameters keyword-only, a JSON body as a model or a mapping (or
  its fields as keywords), the success response parsed into its model.

`--check` regenerates in a temporary directory and fails when the committed
files differ (the drift test runs it).
"""

from __future__ import annotations

import argparse
import copy
import json
import keyword
import re
import subprocess
import sys
import tempfile
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OPENAPI = ROOT.parent.parent / "packages" / "api" / "openapi.json"
OUT_DIR = ROOT / "src" / "kindgi" / "client"
MODELS = "_models.py"
RESOURCES = "_resources.py"
METHODS = ("get", "post", "put", "patch", "delete")

HEADER = """# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2026 Kindgi Inc.
#
# Generated by scripts/gen_client.py from @kindgi/api's openapi.json — do not edit.
"""


# ---------------------------------------------------------------------------
# Names
# ---------------------------------------------------------------------------


def snake(name: str) -> str:
    out = re.sub(r"(?<=[a-z0-9])(?=[A-Z])", "_", name).replace("-", "_").lower()
    return f"{out}_" if keyword.iskeyword(out) else out


def pascal(name: str) -> str:
    return "".join(part[:1].upper() + part[1:] for part in re.split(r"[._\-]", name) if part)


# ---------------------------------------------------------------------------
# The operation table
# ---------------------------------------------------------------------------


@dataclass
class Param:
    name: str  # on the wire
    py: str  # in Python
    where: str  # path | query | header
    required: bool
    annotation: str
    description: str


@dataclass
class Operation:
    id: str
    method: str
    path: str
    summary: str
    description: str
    params: list[Param]
    body: str | None  # model class name
    body_kind: str | None  # json | multipart
    response: str | None  # model class name
    response_kind: str  # json | sse | binary | empty
    status: int

    @property
    def resource(self) -> tuple[str, ...]:
        return tuple(self.id.split(".")[:-1])

    @property
    def name(self) -> str:
        return snake(self.id.split(".")[-1])


@dataclass
class Resource:
    path: tuple[str, ...]
    operations: list[Operation] = field(default_factory=list)
    children: dict[str, Resource] = field(default_factory=dict)

    @property
    def class_name(self) -> str:
        return "".join(pascal(p) for p in self.path) + "Resource"


def deref(doc: dict[str, Any], schema: dict[str, Any]) -> dict[str, Any]:
    while "$ref" in schema:
        schema = doc["components"]["schemas"][schema["$ref"].split("/")[-1]]
    return schema


def param_annotation(doc: dict[str, Any], schema: dict[str, Any]) -> str:
    resolved = deref(doc, schema)
    if "enum" in resolved:
        return "Literal[" + ", ".join(json.dumps(v) for v in resolved["enum"]) + "]"
    kind = resolved.get("type")
    return {"string": "str", "integer": "int", "number": "float", "boolean": "bool"}.get(
        kind if isinstance(kind, str) else "", "Any"
    )


def hoist(doc: dict[str, Any], schema: dict[str, Any], name: str) -> str:
    """The component name for `schema`, adding it to the components when inline."""
    if "$ref" in schema:
        return schema["$ref"].split("/")[-1]
    components = doc["components"]["schemas"]
    if name in components:
        raise SystemExit(f"gen_client: hoisted name {name} collides with a component")
    components[name] = schema
    return name


def operations(source: dict[str, Any]) -> tuple[dict[str, Any], list[Operation]]:
    doc = copy.deepcopy(source)
    ops: list[Operation] = []
    for path, item in doc["paths"].items():
        for method in METHODS:
            op = item.get(method)
            if op is None:
                continue
            op_id: str = op["operationId"]
            params: list[Param] = []
            for raw in [*item.get("parameters", []), *op.get("parameters", [])]:
                p = deref(doc, raw) if "$ref" in raw else raw
                py = {"Idempotency-Key": "idempotency_key", "Last-Event-Id": "last_event_id"}.get(
                    p["name"], snake(p["name"].removeprefix("X-").replace("-", "_"))
                )
                params.append(
                    Param(
                        name=p["name"],
                        py=py,
                        where=p["in"],
                        required=bool(p.get("required", p["in"] == "path")),
                        annotation=param_annotation(doc, p.get("schema", {})),
                        description=p.get("description", ""),
                    )
                )
            # Path parameters in template order.
            order = re.findall(r"{([^}]+)}", path)
            params.sort(
                key=lambda p: (p.where != "path", order.index(p.name) if p.name in order else 0)
            )

            body = body_kind = None
            request = op.get("requestBody")
            if request is not None:
                content = request["content"]
                if "application/json" in content:
                    body_kind = "json"
                    body = hoist(doc, content["application/json"]["schema"], pascal(op_id) + "Body")
                elif "multipart/form-data" in content:
                    body_kind = "multipart"

            status, response, response_kind = 204, None, "empty"
            for code, answer in sorted(op.get("responses", {}).items()):
                if not code.startswith("2"):
                    continue
                status = int(code)
                content = answer.get("content", {})
                if "text/event-stream" in content:
                    response_kind = "sse"
                    response = hoist(
                        doc, content["text/event-stream"]["schema"], pascal(op_id) + "Event"
                    )
                elif "application/json" in content:
                    response_kind = "json"
                    response = hoist(
                        doc, content["application/json"]["schema"], pascal(op_id) + "Response"
                    )
                elif content:
                    response_kind = "binary"
                break
            ops.append(
                Operation(
                    id=op_id,
                    method=method.upper(),
                    path=path,
                    summary=op.get("summary", "").strip(),
                    description=op.get("description", "").strip(),
                    params=params,
                    body=body,
                    body_kind=body_kind,
                    response=response,
                    response_kind=response_kind,
                    status=status,
                )
            )
    return doc, ops


def tree(ops: list[Operation]) -> Resource:
    root = Resource(path=())
    for op in ops:
        node = root
        for depth in range(1, len(op.resource) + 1):
            segment = op.resource[depth - 1]
            node = node.children.setdefault(segment, Resource(path=op.resource[:depth]))
        node.operations.append(op)
    return root


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------


def docstring(op: Operation, indent: str) -> str:
    first = op.summary or op.id
    lines = [f"{first.rstrip('.')}. `{op.method} {op.path}`"]
    if op.description:
        paragraph = op.description.split("\n\n")[0].replace('"""', "'''").replace("\\", "\\\\")
        lines += ["", *paragraph.splitlines()]
    body = "\n".join(f"{indent}{line}" if line else "" for line in lines)
    return f'{indent}"""{body.lstrip()}\n{indent}"""'


def signature(op: Operation, asynchronous: bool) -> str:
    parts = ["self"]
    for p in op.params:
        if p.where == "path":
            parts.append(f"{p.py}: {p.annotation}")
    if op.body_kind == "json":
        parts.append(f"body: _models.{op.body} | Mapping[str, Any] | None = None")
    if op.body_kind == "multipart":
        parts.append("files: Mapping[str, Any]")
    parts.append("/")
    parts.append("*")
    for p in op.params:
        if p.where != "path":
            default = "" if p.required else " = None"
            annotation = p.annotation if p.required else f"{p.annotation} | None"
            parts.append(f"{p.py}: {annotation}{default}")
    if op.body_kind == "multipart":
        parts.append("data: Mapping[str, Any] | None = None")
    parts.append("timeout: float | None = None")
    if op.body_kind == "json":
        parts.append("**fields: Any")
    returns = {
        "json": f"_models.{op.response}",
        "empty": "None",
        "binary": "bytes",
        "sse": f"{'AsyncIterator' if asynchronous else 'Iterator'}[_models.{op.response}]",
    }[op.response_kind]
    prefix = "async def" if asynchronous and op.response_kind != "sse" else "def"
    return f"    {prefix} {op.name}({', '.join(parts)}) -> {returns}:"


def call(op: Operation, asynchronous: bool) -> str:
    def mapping(where: str) -> str:
        items = [f'"{p.name}": {p.py}' for p in op.params if p.where == where]
        return "{" + ", ".join(items) + "}"

    args = [f'_OPERATIONS["{op.id}"]', f"path={mapping('path')}", f"query={mapping('query')}"]
    args.append(f"headers={mapping('header')}")
    if op.body_kind == "json":
        args.append(f"body=_body(_models.{op.body}, body, fields)")
    if op.body_kind == "multipart":
        args.append("files=files")
        args.append("data=data")
    if op.response_kind in ("json", "sse"):
        args.append(f"response=_models.{op.response}")
    args.append("timeout=timeout")
    inner = ", ".join(args)
    if op.response_kind == "sse":
        return f"        return self._client._stream({inner})"
    keyword_await = "await " if asynchronous else ""
    return f"        return {keyword_await}self._client._request({inner})"


def render_resource(node: Resource, asynchronous: bool) -> list[str]:
    name = ("Async" if asynchronous else "") + node.class_name
    client = "AsyncClientBase" if asynchronous else "SyncClientBase"
    out: list[str] = []
    for child in node.children.values():
        out += render_resource(child, asynchronous)
    title = ".".join(node.path)
    out += [
        "",
        "",
        f"class {name}:",
        f'    """`client.{".".join(snake(p) for p in node.path)}` — the `{title}` operations."""',
        "",
        f"    def __init__(self, client: {client}) -> None:",
        "        self._client = client",
    ]
    for segment, child in node.children.items():
        out.append(
            f"        self.{snake(segment)} = "
            f"{'Async' if asynchronous else ''}{child.class_name}(client)"
        )
    for op in node.operations:
        out += ["", signature(op, asynchronous), docstring(op, "        "), call(op, asynchronous)]
    return out


def idempotent(op: Operation) -> str:
    return "True" if any(p.name == "Idempotency-Key" for p in op.params) else "False"


def render_resources(root: Resource, ops: list[Operation]) -> str:
    lines = [
        HEADER,
        "from __future__ import annotations",
        "",
        "from collections.abc import AsyncIterator, Iterator, Mapping",
        "from typing import Any, Literal, cast",
        "",
        "from . import _models",
        "from ._base import AsyncClientBase, Operation, SyncClientBase, _body",
        "",
        '__all__ = ["OPERATIONS", "AsyncResources", "Resources"]',
        "",
        "_ = Literal  # used in generated annotations",
        "",
        "OPERATIONS: dict[str, Operation] = {",
    ]
    for op in ops:
        lines.append(
            f'    "{op.id}": Operation("{op.id}", "{op.method}", "{op.path}", '
            f'"{op.response_kind}", {idempotent(op)}),'
        )
    lines += ["}", "_OPERATIONS = OPERATIONS"]
    for asynchronous in (False, True):
        for child in root.children.values():
            lines += render_resource(child, asynchronous)
    for asynchronous in (False, True):
        prefix = "Async" if asynchronous else ""
        base = "AsyncClientBase" if asynchronous else "SyncClientBase"
        lines += [
            "",
            "",
            f"class {prefix}Resources:",
            f'    """Every resource, as attributes of `{prefix}Kindgi`."""',
            "",
        ]
        for segment, child in root.children.items():
            lines.append(f"    {snake(segment)}: {prefix}{child.class_name}")
        lines += ["", "    def __init__(self) -> None:", f"        client = cast({base}, self)"]
        for segment, child in root.children.items():
            lines.append(f"        self.{snake(segment)} = {prefix}{child.class_name}(client)")
    return "\n".join(lines) + "\n"


def render_models(doc: dict[str, Any], out: Path) -> None:
    """datamodel-code-generator's CLI (its library API changes between releases)."""
    with tempfile.TemporaryDirectory() as tmp:
        source = Path(tmp) / "openapi.json"
        source.write_text(json.dumps(doc), "utf-8")
        header = Path(tmp) / "header.txt"
        header.write_text(HEADER.rstrip("\n") + "\n", "utf-8")
        codegen = Path(sys.executable).parent / "datamodel-codegen"
        subprocess.run(
            [
                str(codegen),
                "--input",
                str(source),
                "--input-file-type",
                "openapi",
                "--output",
                str(out),
                "--output-model-type",
                "pydantic_v2.BaseModel",
                "--target-python-version",
                "3.11",
                "--formatters",
                "ruff-format",
                "--use-standard-collections",
                "--use-union-operator",
                "--field-constraints",
                "--snake-case-field",
                "--allow-population-by-field-name",
                "--use-annotated",
                "--enum-field-as-literal",
                "all",
                "--use-schema-description",
                "--use-field-description",
                "--disable-timestamp",
                "--capitalise-enum-members",
                "--collapse-root-models",
                "--extra-fields",
                "allow",
                "--custom-file-header-path",
                str(header),
            ],
            check=True,
            cwd=ROOT,
        )


def generate_into(openapi: Path, out_dir: Path) -> list[Path]:
    source = json.loads(openapi.read_text("utf-8"))
    doc, ops = operations(source)
    seen: set[str] = set()
    for op in ops:
        if op.id in seen:
            raise SystemExit(f"gen_client: duplicate operationId {op.id}")
        seen.add(op.id)
    out_dir.mkdir(parents=True, exist_ok=True)
    models = out_dir / MODELS
    render_models(doc, models)
    resources = out_dir / RESOURCES
    resources.write_text(render_resources(tree(ops), ops), "utf-8")
    files = [models, resources]
    ruff = Path(sys.executable).parent / "ruff"
    subprocess.run([str(ruff), "format", "--quiet", *map(str, files)], check=True, cwd=ROOT)
    subprocess.run(
        [str(ruff), "check", "--quiet", "--fix", "--select", "I,F401,UP", *map(str, files)],
        check=False,
        cwd=ROOT,
    )
    subprocess.run([str(ruff), "format", "--quiet", *map(str, files)], check=True, cwd=ROOT)
    return files


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--openapi", type=Path, default=DEFAULT_OPENAPI)
    parser.add_argument("--check", action="store_true", help="fail when the committed files differ")
    args = parser.parse_args(argv)
    if not args.check:
        for path in generate_into(args.openapi, OUT_DIR):
            print(f"wrote {path.relative_to(ROOT)}")
        return 0
    # Under ROOT, so ruff finds this project's line length, as it does in OUT_DIR.
    with tempfile.TemporaryDirectory(dir=ROOT) as tmp:
        stale = []
        for path in generate_into(args.openapi, Path(tmp)):
            committed = OUT_DIR / path.name
            if not committed.is_file() or committed.read_text("utf-8") != path.read_text("utf-8"):
                stale.append(path.name)
        if stale:
            print(
                f"stale: {', '.join(stale)} — run `uv run python scripts/gen_client.py`",
                file=sys.stderr,
            )
            return 1
    print("kindgi.client is in step with openapi.json")
    return 0


if __name__ == "__main__":
    sys.exit(main())
