// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Kindgi Inc.

// Generated by scripts/gen-webhook-event-shapes.mjs from packages/api/openapi.json (WebhookEvent).
// Don't edit: run `pnpm run gen:webhook-shapes`. CI checks it's current (`check:webhook-shapes`).

import type { WebhookEvent } from '@kindgi/client';

import type { EventShape } from './webhook-events.js';

/** Each event `type` the API sends, and its shape. */
export const WEBHOOK_EVENT_SHAPES = {
  'run.finished': {
    kind: 'object',
    required: {
      id: {
        kind: 'string',
      },
      type: {
        kind: 'string',
        enum: ['run.finished'],
      },
      createdAt: {
        kind: 'string',
        format: 'date-time',
      },
      data: {
        kind: 'object',
        required: {
          run: {
            kind: 'object',
            required: {
              id: {
                kind: 'string',
                format: 'uuid',
              },
              projectId: {
                kind: 'string',
                format: 'uuid',
              },
              flowId: {
                kind: 'string',
              },
              flowVersion: {
                kind: 'string',
              },
              status: {
                kind: 'string',
                enum: ['completed', 'failed', 'cancelled'],
              },
              dryRun: {
                kind: 'boolean',
              },
              failureMessage: {
                kind: 'string',
                nullable: true,
              },
              createdAt: {
                kind: 'string',
                format: 'date-time',
              },
              completedAt: {
                kind: 'string',
                format: 'date-time',
              },
            },
            optional: {
              usage: {
                kind: 'object',
                required: {
                  calls: {
                    kind: 'integer',
                    minimum: 0,
                  },
                  costUsd: {
                    kind: 'number',
                    minimum: 0,
                  },
                  tokens: {
                    kind: 'object',
                    required: {
                      prompt: {
                        kind: 'integer',
                        minimum: 0,
                      },
                      completion: {
                        kind: 'integer',
                        minimum: 0,
                      },
                      cacheRead: {
                        kind: 'integer',
                        minimum: 0,
                      },
                      cacheWrite: {
                        kind: 'integer',
                        minimum: 0,
                      },
                      reasoning: {
                        kind: 'integer',
                        minimum: 0,
                      },
                    },
                  },
                },
              },
              agent: {
                kind: 'object',
                required: {
                  id: {
                    kind: 'string',
                  },
                  version: {
                    kind: 'string',
                  },
                  conversationId: {
                    kind: 'string',
                    format: 'uuid',
                  },
                },
                optional: {
                  via: {
                    kind: 'string',
                    enum: ['explicit', 'flow-pin', 'conversation', 'live', 'latest'],
                  },
                  liveScope: {
                    kind: 'union',
                    discriminator: 'kind',
                    variants: {
                      tenant: {
                        kind: 'object',
                        required: {
                          kind: {
                            kind: 'string',
                            enum: ['tenant'],
                          },
                        },
                      },
                      org: {
                        kind: 'object',
                        required: {
                          kind: {
                            kind: 'string',
                            enum: ['org'],
                          },
                          orgId: {
                            kind: 'string',
                            format: 'uuid',
                          },
                        },
                      },
                      project: {
                        kind: 'object',
                        required: {
                          kind: {
                            kind: 'string',
                            enum: ['project'],
                          },
                          projectId: {
                            kind: 'string',
                            format: 'uuid',
                          },
                        },
                      },
                      segment: {
                        kind: 'object',
                        required: {
                          kind: {
                            kind: 'string',
                            enum: ['segment'],
                          },
                          projectId: {
                            kind: 'string',
                            format: 'uuid',
                          },
                          path: {
                            kind: 'array',
                            minItems: 1,
                            maxItems: 8,
                            items: {
                              kind: 'object',
                              required: {
                                key: {
                                  kind: 'string',
                                  pattern: '^[a-z][a-z0-9_-]{0,63}$',
                                },
                                value: {
                                  kind: 'string',
                                  minLength: 1,
                                  maxLength: 256,
                                },
                              },
                            },
                          },
                        },
                      },
                    },
                  },
                },
              },
            },
          },
        },
      },
    },
  },
  'improvement-pass.finished': {
    kind: 'object',
    required: {
      id: {
        kind: 'string',
      },
      type: {
        kind: 'string',
        enum: ['improvement-pass.finished'],
      },
      createdAt: {
        kind: 'string',
        format: 'date-time',
      },
      data: {
        kind: 'object',
        required: {
          pass: {
            kind: 'object',
            required: {
              id: {
                kind: 'string',
                format: 'uuid',
              },
              agentId: {
                kind: 'string',
              },
              fromVersion: {
                kind: 'string',
              },
              scope: {
                kind: 'union',
                discriminator: 'kind',
                variants: {
                  tenant: {
                    kind: 'object',
                    required: {
                      kind: {
                        kind: 'string',
                        enum: ['tenant'],
                      },
                    },
                  },
                  org: {
                    kind: 'object',
                    required: {
                      kind: {
                        kind: 'string',
                        enum: ['org'],
                      },
                      orgId: {
                        kind: 'string',
                        format: 'uuid',
                      },
                    },
                  },
                  project: {
                    kind: 'object',
                    required: {
                      kind: {
                        kind: 'string',
                        enum: ['project'],
                      },
                      projectId: {
                        kind: 'string',
                        format: 'uuid',
                      },
                    },
                  },
                  segment: {
                    kind: 'object',
                    required: {
                      kind: {
                        kind: 'string',
                        enum: ['segment'],
                      },
                      projectId: {
                        kind: 'string',
                        format: 'uuid',
                      },
                      path: {
                        kind: 'array',
                        minItems: 1,
                        maxItems: 8,
                        items: {
                          kind: 'object',
                          required: {
                            key: {
                              kind: 'string',
                              pattern: '^[a-z][a-z0-9_-]{0,63}$',
                            },
                            value: {
                              kind: 'string',
                              minLength: 1,
                              maxLength: 256,
                            },
                          },
                        },
                      },
                    },
                  },
                },
              },
              suiteId: {
                kind: 'string',
              },
              tiers: {
                kind: 'array',
                items: {
                  kind: 'string',
                  enum: ['settings', 'prompt'],
                },
              },
              objective: {
                kind: 'string',
                enum: ['weightedYesShare', 'weightedPrecisionAtK'],
              },
              budget: {
                kind: 'object',
                required: {
                  maxCostUsd: {
                    kind: 'number',
                    maximum: 100,
                    exclusiveMinimum: 0,
                  },
                  maxCandidates: {
                    kind: 'integer',
                    minimum: 1,
                    maximum: 200,
                  },
                },
              },
              requestedBy: {
                kind: 'string',
              },
              status: {
                kind: 'string',
                enum: ['running', 'completed', 'failed', 'cancelled'],
              },
              candidatesEvaluated: {
                kind: 'integer',
                minimum: 0,
              },
              costUsd: {
                kind: 'string',
              },
              createdAt: {
                kind: 'string',
                format: 'date-time',
              },
              updatedAt: {
                kind: 'string',
                format: 'date-time',
              },
            },
            optional: {
              classWeights: {
                kind: 'string',
                enum: ['as-recorded', 'restricted-only'],
              },
              model: {
                kind: 'object',
                required: {
                  providerId: {
                    kind: 'string',
                  },
                  model: {
                    kind: 'string',
                  },
                },
              },
              candidates: {
                kind: 'integer',
                minimum: 1,
                maximum: 5,
              },
              outcome: {
                kind: 'object',
                required: {
                  kind: {
                    kind: 'string',
                    enum: ['proposed', 'nothing-found', 'failed'],
                  },
                },
                optional: {
                  proposalId: {
                    kind: 'string',
                    format: 'uuid',
                  },
                  reason: {
                    kind: 'string',
                  },
                  holdOut: {
                    kind: 'object',
                    required: {
                      baseline: {
                        kind: 'number',
                        nullable: true,
                      },
                      candidate: {
                        kind: 'number',
                        nullable: true,
                      },
                      delta: {
                        kind: 'number',
                        nullable: true,
                      },
                    },
                    optional: {
                      spread: {
                        kind: 'number',
                      },
                    },
                  },
                  message: {
                    kind: 'string',
                  },
                },
              },
              comparisons: {
                kind: 'array',
                items: {
                  kind: 'object',
                  required: {
                    role: {
                      kind: 'string',
                      enum: ['reference', 'candidate', 'proof'],
                    },
                    part: {
                      kind: 'string',
                      enum: ['search', 'hold-out'],
                    },
                  },
                  optional: {
                    evalRunId: {
                      kind: 'string',
                      format: 'uuid',
                    },
                    blockId: {
                      kind: 'string',
                    },
                    changed: {
                      kind: 'object',
                    },
                    score: {
                      kind: 'number',
                      nullable: true,
                    },
                    failed: {
                      kind: 'string',
                    },
                    refused: {
                      kind: 'array',
                      items: {
                        kind: 'object',
                        required: {
                          path: {
                            kind: 'string',
                          },
                          message: {
                            kind: 'string',
                          },
                        },
                      },
                    },
                    hypothesis: {
                      kind: 'string',
                    },
                  },
                },
              },
              trigger: {
                kind: 'object',
                required: {
                  triggerId: {
                    kind: 'string',
                  },
                  fireId: {
                    kind: 'string',
                  },
                },
              },
              finishedAt: {
                kind: 'string',
                format: 'date-time',
              },
            },
          },
        },
      },
    },
  },
  'approval.requested': {
    kind: 'object',
    required: {
      id: {
        kind: 'string',
      },
      type: {
        kind: 'string',
        enum: ['approval.requested'],
      },
      createdAt: {
        kind: 'string',
        format: 'date-time',
      },
      data: {
        kind: 'object',
        required: {
          approval: {
            kind: 'object',
            required: {
              approvalId: {
                kind: 'string',
              },
              requiredRole: {
                kind: 'string',
                enum: ['standard', 'senior', 'admin'],
              },
              createdAt: {
                kind: 'string',
                format: 'date-time',
              },
            },
            optional: {
              projectId: {
                kind: 'string',
              },
              title: {
                kind: 'string',
              },
              assignedTo: {
                kind: 'string',
              },
              expiresAt: {
                kind: 'string',
                format: 'date-time',
              },
              url: {
                kind: 'string',
              },
            },
          },
        },
      },
    },
  },
  'webhook.test': {
    kind: 'object',
    required: {
      id: {
        kind: 'string',
      },
      type: {
        kind: 'string',
        enum: ['webhook.test'],
      },
      createdAt: {
        kind: 'string',
        format: 'date-time',
      },
      data: {
        kind: 'object',
        required: {
          endpointId: {
            kind: 'string',
          },
        },
      },
    },
  },
} as const satisfies Readonly<Record<WebhookEvent['type'], EventShape>>;
