// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Kindgi Inc.
//
// Generated by kindgi-codegen-maven-plugin from the Kindgi API's openapi.json; do not edit.
package com.kindgi.client.internal.codec;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import com.kindgi.client.models.Baseline;
import java.util.Map;
import tools.jackson.core.JsonParser;
import tools.jackson.core.JsonToken;
import tools.jackson.databind.DeserializationContext;
import tools.jackson.databind.JsonNode;
import tools.jackson.databind.ValueDeserializer;
import tools.jackson.databind.annotation.JsonDeserialize;
import tools.jackson.databind.module.SimpleModule;

/**
 * The client's JSON codec for {@link Baseline}.
 */
final class BaselineJson {
    private BaselineJson() {
    }

    static void register(SimpleModule module) {
        module.setMixInAnnotation(Baseline.Recorded.class, BaselineRecordedMixIn.class);
        module.setMixInAnnotation(Baseline.class, BaselineMixIn.class);
        module.setMixInAnnotation(Baseline.Unrecognized.class, BaselineUnrecognizedMixIn.class);
        module.setMixInAnnotation(Baseline.WithAgentId.class, BaselineWithAgentIdMixIn.class);
        module.setMixInAnnotation(Baseline.WithLive.class, BaselineWithLiveMixIn.class);
        module.setMixInAnnotation(Baseline.WithLive.Live.class, BaselineWithLiveLiveMixIn.class);
    }

    /**
     * Reads a {@link Baseline}: a string is its text, an object one of its object variants.
     */
    static final class BaselineCodec extends ValueDeserializer<Baseline> {
        @Override
        public Baseline deserialize(JsonParser p, DeserializationContext ctxt) {
            if (p.currentToken() == JsonToken.VALUE_STRING) {
                return new Baseline.Recorded(p.getString());
            }
            if (p.currentToken() != JsonToken.START_OBJECT) {
                return (Baseline) ctxt.handleUnexpectedToken(Baseline.class, p);
            }
            JsonNode node = ctxt.readTree(p);
            if (node.has("agentId")) {
                return ctxt.readTreeAsValue(node, Baseline.WithAgentId.class);
            }
            if (node.has("live")) {
                return ctxt.readTreeAsValue(node, Baseline.WithLive.class);
            }
            return ctxt.readTreeAsValue(node, Baseline.Unrecognized.class);
        }
    }

    abstract static class BaselineRecordedMixIn {
        @JsonValue
        abstract String value();
    }

    @JsonDeserialize(
            using = BaselineCodec.class
    )
    interface BaselineMixIn {
    }

    @JsonDeserialize(
            using = ValueDeserializer.None.class
    )
    abstract static class BaselineUnrecognizedMixIn {
        BaselineUnrecognizedMixIn(@JsonAnySetter Map<String, Object> properties) {
        }

        @JsonAnyGetter
        abstract Map<String, Object> properties();
    }

    @JsonDeserialize(
            using = ValueDeserializer.None.class
    )
    abstract static class BaselineWithAgentIdMixIn {
        @JsonProperty("agentId")
        abstract String agentId();

        @JsonProperty("version")
        abstract String version();
    }

    @JsonDeserialize(
            using = ValueDeserializer.None.class
    )
    abstract static class BaselineWithLiveMixIn {
        @JsonProperty("live")
        abstract Baseline.WithLive.Live live();
    }

    abstract static class BaselineWithLiveLiveMixIn {
        @JsonProperty("projectId")
        abstract String projectId();
    }
}
