// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Kindgi Inc.
//
// Generated by kindgi-codegen-maven-plugin from the Kindgi API's openapi.json; do not edit.
package com.kindgi.client.internal.codec;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.kindgi.client.models.Circle;
import tools.jackson.databind.module.SimpleModule;

/**
 * The client's JSON codec for {@link Circle}.
 */
final class CircleJson {
    private CircleJson() {
    }

    static void register(SimpleModule module) {
        module.setMixInAnnotation(Circle.class, CircleMixIn.class);
    }

    abstract static class CircleMixIn {
        @JsonProperty("kind")
        abstract String kind();

        @JsonProperty("radius")
        abstract Double radius();
    }
}
