// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Kindgi Inc.
//
// Generated by kindgi-codegen-maven-plugin from the Kindgi API's openapi.json; do not edit.
package com.kindgi.client.internal.codec;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.kindgi.client.models.Content;
import java.util.Map;
import tools.jackson.databind.module.SimpleModule;

/**
 * The client's JSON codec for {@link Content}.
 */
final class ContentJson {
    private ContentJson() {
    }

    static void register(SimpleModule module) {
        module.setMixInAnnotation(Content.class, ContentMixIn.class);
        module.setMixInAnnotation(Content.Unrecognized.class, ContentUnrecognizedMixIn.class);
        module.setMixInAnnotation(Content.WithText.class, ContentWithTextMixIn.class);
        module.setMixInAnnotation(Content.WithValues.class, ContentWithValuesMixIn.class);
    }

    @JsonTypeInfo(
            use = JsonTypeInfo.Id.DEDUCTION,
            defaultImpl = Content.Unrecognized.class
    )
    @JsonSubTypes({
            @JsonSubTypes.Type(Content.WithText.class),
            @JsonSubTypes.Type(Content.WithValues.class)
    })
    interface ContentMixIn {
    }

    abstract static class ContentUnrecognizedMixIn {
        ContentUnrecognizedMixIn(@JsonAnySetter Map<String, Object> properties) {
        }

        @JsonAnyGetter
        abstract Map<String, Object> properties();
    }

    abstract static class ContentWithTextMixIn {
        @JsonProperty("text")
        abstract String text();
    }

    abstract static class ContentWithValuesMixIn {
        @JsonProperty("values")
        abstract Map<String, Object> values();
    }
}
