// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Kindgi Inc.
//
// Generated by kindgi-codegen-maven-plugin from the Kindgi API's openapi.json; do not edit.
package com.kindgi.client.internal.codec;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.kindgi.client.models.CreatedEvent;
import com.kindgi.client.models.Widget;
import tools.jackson.databind.module.SimpleModule;

/**
 * The client's JSON codec for {@link CreatedEvent}.
 */
final class CreatedEventJson {
    private CreatedEventJson() {
    }

    static void register(SimpleModule module) {
        module.setMixInAnnotation(CreatedEvent.class, CreatedEventMixIn.class);
    }

    abstract static class CreatedEventMixIn {
        @JsonProperty("type")
        abstract String type();

        @JsonProperty("widget")
        abstract Widget widget();
    }
}
