// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Kindgi Inc.
//
// Generated by kindgi-codegen-maven-plugin from the Kindgi API's openapi.json; do not edit.
package com.kindgi.client.internal.codec;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.kindgi.client.models.CreateWidgetBody;
import com.kindgi.client.models.Shape;
import com.kindgi.client.models.WidgetState;
import tools.jackson.databind.module.SimpleModule;

/**
 * The client's JSON codec for {@link CreateWidgetBody}.
 */
final class CreateWidgetBodyJson {
    private CreateWidgetBodyJson() {
    }

    static void register(SimpleModule module) {
        module.setMixInAnnotation(CreateWidgetBody.class, CreateWidgetBodyMixIn.class);
    }

    abstract static class CreateWidgetBodyMixIn {
        @JsonProperty("name")
        abstract String name();

        @JsonProperty("state")
        abstract WidgetState state();

        @JsonProperty("shape")
        abstract Shape shape();
    }
}
