// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Kindgi Inc.
//
// Generated by kindgi-codegen-maven-plugin from the Kindgi API's openapi.json; do not edit.
package com.kindgi.client.internal.codec;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.kindgi.client.models.DeletedEvent;
import java.util.UUID;
import tools.jackson.databind.module.SimpleModule;

/**
 * The client's JSON codec for {@link DeletedEvent}.
 */
final class DeletedEventJson {
    private DeletedEventJson() {
    }

    static void register(SimpleModule module) {
        module.setMixInAnnotation(DeletedEvent.class, DeletedEventMixIn.class);
    }

    abstract static class DeletedEventMixIn {
        @JsonProperty("type")
        abstract String type();

        @JsonProperty("widgetId")
        abstract UUID widgetId();
    }
}
