// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Kindgi Inc.
//
// Generated by kindgi-codegen-maven-plugin from the Kindgi API's openapi.json; do not edit.
package com.kindgi.client.internal.codec;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.kindgi.client.models.Flow;
import java.util.Map;
import tools.jackson.databind.module.SimpleModule;

/**
 * The client's JSON codec for {@link Flow}.
 */
final class FlowJson {
    private FlowJson() {
    }

    static void register(SimpleModule module) {
        module.setMixInAnnotation(Flow.class, FlowMixIn.class);
    }

    abstract static class FlowMixIn {
        FlowMixIn(@JsonProperty("id") String id,
                @JsonAnySetter Map<String, Object> additionalProperties) {
        }

        @JsonProperty("id")
        abstract String id();

        @JsonAnyGetter
        abstract Map<String, Object> additionalProperties();
    }
}
