// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Kindgi Inc.
//
// Generated by kindgi-codegen-maven-plugin from the Kindgi API's openapi.json; do not edit.
package com.kindgi.client.internal.codec;

import tools.jackson.databind.module.SimpleModule;

/**
 * The client's JSON codec for every model.
 */
public final class ModelCodecs {
    private ModelCodecs() {
    }

    /**
     * Adds every model's codec to {@code module}.
     *
     * @param module the client's module
     */
    public static void register(SimpleModule module) {
        WidgetInstructionsJson.register(module);
        WidgetJson.register(module);
        WidgetStateJson.register(module);
        ShapeJson.register(module);
        CircleJson.register(module);
        SquareJson.register(module);
        ContentJson.register(module);
        PromptRefJson.register(module);
        BaselineJson.register(module);
        WidgetPageJson.register(module);
        WidgetCoreJson.register(module);
        CreateWidgetBodyJson.register(module);
        PatchWidgetBodyJson.register(module);
        OwnerJson.register(module);
        WidgetEventJson.register(module);
        CreatedEventJson.register(module);
        DeletedEventJson.register(module);
        UploadBodyJson.register(module);
        RotateDoneJson.register(module);
        RotateQueuedJson.register(module);
        FlowJson.register(module);
        NodeJson.register(module);
        ScopeSegmentJson.register(module);
        WidgetsRotateResponseJson.register(module);
        SettingsPutDomainJson.register(module);
        SettingsPutBodyJson.register(module);
        SettingsPutResponseJson.register(module);
    }
}
