// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Kindgi Inc.
//
// Generated by kindgi-codegen-maven-plugin from the Kindgi API's openapi.json; do not edit.
package com.kindgi.client.internal.codec;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.kindgi.client.models.Node;
import java.util.List;
import tools.jackson.databind.module.SimpleModule;

/**
 * The client's JSON codec for {@link Node}.
 */
final class NodeJson {
    private NodeJson() {
    }

    static void register(SimpleModule module) {
        module.setMixInAnnotation(Node.class, NodeMixIn.class);
    }

    abstract static class NodeMixIn {
        @JsonProperty("id")
        abstract String id();

        @JsonProperty("children")
        abstract List<Node> children();
    }
}
