// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Kindgi Inc.
//
// Generated by kindgi-codegen-maven-plugin from the Kindgi API's openapi.json; do not edit.
package com.kindgi.client.internal.codec;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.kindgi.client.models.Owner;
import tools.jackson.databind.module.SimpleModule;

/**
 * The client's JSON codec for {@link Owner}.
 */
final class OwnerJson {
    private OwnerJson() {
    }

    static void register(SimpleModule module) {
        module.setMixInAnnotation(Owner.class, OwnerMixIn.class);
    }

    abstract static class OwnerMixIn {
        @JsonProperty("id")
        abstract String id();
    }
}
