// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Kindgi Inc.
//
// Generated by kindgi-codegen-maven-plugin from the Kindgi API's openapi.json; do not edit.
package com.kindgi.client.internal.codec;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.kindgi.client.models.OptionalNullable;
import com.kindgi.client.models.Owner;
import com.kindgi.client.models.PatchWidgetBody;
import tools.jackson.databind.module.SimpleModule;

/**
 * The client's JSON codec for {@link PatchWidgetBody}.
 */
final class PatchWidgetBodyJson {
    private PatchWidgetBodyJson() {
    }

    static void register(SimpleModule module) {
        module.setMixInAnnotation(PatchWidgetBody.class, PatchWidgetBodyMixIn.class);
    }

    abstract static class PatchWidgetBodyMixIn {
        @JsonProperty("name")
        abstract String name();

        @JsonProperty("note")
        @JsonInclude(
                value = JsonInclude.Include.CUSTOM,
                valueFilter = OptionalNullable.AbsentFilter.class
        )
        abstract OptionalNullable<String> note();

        @JsonProperty("owner")
        @JsonInclude(
                value = JsonInclude.Include.CUSTOM,
                valueFilter = OptionalNullable.AbsentFilter.class
        )
        abstract OptionalNullable<Owner> owner();
    }
}
