// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Kindgi Inc.
//
// Generated by kindgi-codegen-maven-plugin from the Kindgi API's openapi.json; do not edit.
package com.kindgi.client.internal.codec;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.kindgi.client.models.PromptRef;
import tools.jackson.databind.ValueDeserializer;
import tools.jackson.databind.annotation.JsonDeserialize;
import tools.jackson.databind.module.SimpleModule;

/**
 * The client's JSON codec for {@link PromptRef}.
 */
final class PromptRefJson {
    private PromptRefJson() {
    }

    static void register(SimpleModule module) {
        module.setMixInAnnotation(PromptRef.class, PromptRefMixIn.class);
    }

    @JsonDeserialize(
            using = ValueDeserializer.None.class
    )
    abstract static class PromptRefMixIn {
        @JsonProperty("kind")
        abstract String kind();

        @JsonProperty("blockId")
        abstract String blockId();
    }
}
