// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Kindgi Inc.
//
// Generated by kindgi-codegen-maven-plugin from the Kindgi API's openapi.json; do not edit.
package com.kindgi.client.internal.codec;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.kindgi.client.models.RotateDone;
import java.time.OffsetDateTime;
import tools.jackson.databind.module.SimpleModule;

/**
 * The client's JSON codec for {@link RotateDone}.
 */
final class RotateDoneJson {
    private RotateDoneJson() {
    }

    static void register(SimpleModule module) {
        module.setMixInAnnotation(RotateDone.class, RotateDoneMixIn.class);
    }

    abstract static class RotateDoneMixIn {
        @JsonProperty("rotatedAt")
        abstract OffsetDateTime rotatedAt();
    }
}
