// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Kindgi Inc.
//
// Generated by kindgi-codegen-maven-plugin from the Kindgi API's openapi.json; do not edit.
package com.kindgi.client.internal.codec;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.kindgi.client.models.RotateQueued;
import tools.jackson.databind.module.SimpleModule;

/**
 * The client's JSON codec for {@link RotateQueued}.
 */
final class RotateQueuedJson {
    private RotateQueuedJson() {
    }

    static void register(SimpleModule module) {
        module.setMixInAnnotation(RotateQueued.class, RotateQueuedMixIn.class);
    }

    abstract static class RotateQueuedMixIn {
        @JsonProperty("jobId")
        abstract String jobId();
    }
}
