// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Kindgi Inc.
//
// Generated by kindgi-codegen-maven-plugin from the Kindgi API's openapi.json; do not edit.
package com.kindgi.client.internal.codec;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.kindgi.client.models.ScopeSegment;
import tools.jackson.databind.module.SimpleModule;

/**
 * The client's JSON codec for {@link ScopeSegment}.
 */
final class ScopeSegmentJson {
    private ScopeSegmentJson() {
    }

    static void register(SimpleModule module) {
        module.setMixInAnnotation(ScopeSegment.class, ScopeSegmentMixIn.class);
    }

    abstract static class ScopeSegmentMixIn {
        @JsonProperty("key")
        abstract String key();

        @JsonProperty("value")
        abstract String value();
    }
}
