// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Kindgi Inc.
//
// Generated by kindgi-codegen-maven-plugin from the Kindgi API's openapi.json; do not edit.
package com.kindgi.client.internal.codec;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.kindgi.client.models.SettingsPutBody;
import tools.jackson.databind.module.SimpleModule;

/**
 * The client's JSON codec for {@link SettingsPutBody}.
 */
final class SettingsPutBodyJson {
    private SettingsPutBodyJson() {
    }

    static void register(SimpleModule module) {
        module.setMixInAnnotation(SettingsPutBody.class, SettingsPutBodyMixIn.class);
        TextValues.register(module, SettingsPutBody.Mode.class, SettingsPutBody.Mode::of, SettingsPutBody.Mode::asString);
    }

    abstract static class SettingsPutBodyMixIn {
        @JsonProperty("mode")
        abstract SettingsPutBody.Mode mode();
    }
}
