// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Kindgi Inc.
//
// Generated by kindgi-codegen-maven-plugin from the Kindgi API's openapi.json; do not edit.
package com.kindgi.client.internal.codec;

import com.kindgi.client.models.SettingsPutDomain;
import tools.jackson.databind.module.SimpleModule;

/**
 * The client's JSON codec for {@link SettingsPutDomain}.
 */
final class SettingsPutDomainJson {
    private SettingsPutDomainJson() {
    }

    static void register(SimpleModule module) {
        TextValues.register(module, SettingsPutDomain.class, SettingsPutDomain::of, SettingsPutDomain::asString);
    }
}
