// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Kindgi Inc.
//
// Generated by kindgi-codegen-maven-plugin from the Kindgi API's openapi.json; do not edit.
package com.kindgi.client.internal.codec;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.kindgi.client.models.SettingsPutResponse;
import tools.jackson.databind.module.SimpleModule;

/**
 * The client's JSON codec for {@link SettingsPutResponse}.
 */
final class SettingsPutResponseJson {
    private SettingsPutResponseJson() {
    }

    static void register(SimpleModule module) {
        module.setMixInAnnotation(SettingsPutResponse.class, SettingsPutResponseMixIn.class);
    }

    abstract static class SettingsPutResponseMixIn {
        @JsonProperty("applied")
        abstract Boolean applied();
    }
}
