// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Kindgi Inc.
//
// Generated by kindgi-codegen-maven-plugin from the Kindgi API's openapi.json; do not edit.
package com.kindgi.client.internal.codec;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.kindgi.client.models.Circle;
import com.kindgi.client.models.Shape;
import com.kindgi.client.models.Square;
import java.util.Map;
import tools.jackson.databind.module.SimpleModule;

/**
 * The client's JSON codec for {@link Shape}.
 */
final class ShapeJson {
    private ShapeJson() {
    }

    static void register(SimpleModule module) {
        module.setMixInAnnotation(Shape.class, ShapeMixIn.class);
        module.setMixInAnnotation(Shape.Unrecognized.class, ShapeUnrecognizedMixIn.class);
        module.setMixInAnnotation(Shape.DotOrPoint.class, ShapeDotOrPointMixIn.class);
    }

    @JsonTypeInfo(
            use = JsonTypeInfo.Id.NAME,
            include = JsonTypeInfo.As.EXISTING_PROPERTY,
            property = "kind",
            visible = true,
            defaultImpl = Shape.Unrecognized.class
    )
    @JsonSubTypes({
            @JsonSubTypes.Type(value = Circle.class, name = "circle"),
            @JsonSubTypes.Type(value = Square.class, name = "square"),
            @JsonSubTypes.Type(value = Shape.DotOrPoint.class, names = {"dot", "point"})
    })
    interface ShapeMixIn {
    }

    abstract static class ShapeUnrecognizedMixIn {
        ShapeUnrecognizedMixIn(@JsonProperty("kind") String kind,
                @JsonAnySetter Map<String, Object> properties) {
        }

        @JsonProperty("kind")
        abstract String kind();

        @JsonAnyGetter
        abstract Map<String, Object> properties();
    }

    abstract static class ShapeDotOrPointMixIn {
        @JsonProperty("kind")
        abstract String kind();

        @JsonProperty("x")
        abstract Double x();
    }
}
