// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Kindgi Inc.
//
// Generated by kindgi-codegen-maven-plugin from the Kindgi API's openapi.json; do not edit.
package com.kindgi.client.internal.codec;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.kindgi.client.models.Square;
import tools.jackson.databind.module.SimpleModule;

/**
 * The client's JSON codec for {@link Square}.
 */
final class SquareJson {
    private SquareJson() {
    }

    static void register(SimpleModule module) {
        module.setMixInAnnotation(Square.class, SquareMixIn.class);
    }

    abstract static class SquareMixIn {
        @JsonProperty("kind")
        abstract String kind();

        @JsonProperty("side")
        abstract Double side();
    }
}
