// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Kindgi Inc.
//
// Generated by kindgi-codegen-maven-plugin from the Kindgi API's openapi.json; do not edit.
package com.kindgi.client.internal.codec;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.kindgi.client.models.UploadBody;
import java.util.UUID;
import tools.jackson.databind.module.SimpleModule;

/**
 * The client's JSON codec for {@link UploadBody}.
 */
final class UploadBodyJson {
    private UploadBodyJson() {
    }

    static void register(SimpleModule module) {
        module.setMixInAnnotation(UploadBody.class, UploadBodyMixIn.class);
    }

    abstract static class UploadBodyMixIn {
        @JsonProperty("file")
        abstract byte[] file();

        @JsonProperty("name")
        abstract String name();

        @JsonProperty("ownerId")
        abstract UUID ownerId();
    }
}
