// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Kindgi Inc.
//
// Generated by kindgi-codegen-maven-plugin from the Kindgi API's openapi.json; do not edit.
package com.kindgi.client.internal.codec;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.kindgi.client.models.Baseline;
import com.kindgi.client.models.Content;
import com.kindgi.client.models.Flow;
import com.kindgi.client.models.Node;
import com.kindgi.client.models.OptionalNullable;
import com.kindgi.client.models.Owner;
import com.kindgi.client.models.Shape;
import com.kindgi.client.models.Widget;
import com.kindgi.client.models.WidgetInstructions;
import com.kindgi.client.models.WidgetState;
import java.time.OffsetDateTime;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import tools.jackson.databind.module.SimpleModule;

/**
 * The client's JSON codec for {@link Widget}.
 */
final class WidgetJson {
    private WidgetJson() {
    }

    static void register(SimpleModule module) {
        module.setMixInAnnotation(Widget.class, WidgetMixIn.class);
        module.setMixInAnnotation(Widget.Size.class, WidgetSizeMixIn.class);
    }

    abstract static class WidgetMixIn {
        @JsonProperty("id")
        abstract UUID id();

        @JsonProperty("name")
        abstract String name();

        @JsonProperty("state")
        abstract WidgetState state();

        @JsonProperty("label")
        abstract String label();

        @JsonProperty("note")
        @JsonInclude(
                value = JsonInclude.Include.CUSTOM,
                valueFilter = OptionalNullable.AbsentFilter.class
        )
        abstract OptionalNullable<String> note();

        @JsonProperty("createdAt")
        abstract OffsetDateTime createdAt();

        @JsonProperty("tags")
        abstract List<String> tags();

        @JsonProperty("labels")
        abstract Map<String, String> labels();

        @JsonProperty("size")
        abstract Widget.Size size();

        @JsonProperty("kind")
        abstract String kind();

        @JsonProperty("shape")
        abstract Shape shape();

        @JsonProperty("content")
        abstract Content content();

        @JsonProperty("instructions")
        abstract WidgetInstructions instructions();

        @JsonProperty("baseline")
        abstract Baseline baseline();

        @JsonProperty("score")
        abstract Object score();

        @JsonProperty("stamp")
        abstract String stamp();

        @JsonProperty("restricted")
        abstract Boolean restricted();

        @JsonProperty("extra")
        abstract Object extra();

        @JsonProperty("wait")
        abstract Boolean wait_();

        @JsonProperty("default")
        abstract String default_();

        @JsonProperty("owner")
        @JsonInclude(
                value = JsonInclude.Include.CUSTOM,
                valueFilter = OptionalNullable.AbsentFilter.class
        )
        abstract OptionalNullable<Owner> owner();

        @JsonProperty("flow")
        abstract Flow flow();

        @JsonProperty("nodes")
        abstract List<Node> nodes();
    }

    abstract static class WidgetSizeMixIn {
        @JsonProperty("width")
        abstract Long width();

        @JsonProperty("height")
        abstract Double height();
    }
}
