// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Kindgi Inc.
//
// Generated by kindgi-codegen-maven-plugin from the Kindgi API's openapi.json; do not edit.
package com.kindgi.client.internal.codec;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.kindgi.client.models.CreatedEvent;
import com.kindgi.client.models.DeletedEvent;
import com.kindgi.client.models.WidgetEvent;
import java.util.Map;
import tools.jackson.databind.module.SimpleModule;

/**
 * The client's JSON codec for {@link WidgetEvent}.
 */
final class WidgetEventJson {
    private WidgetEventJson() {
    }

    static void register(SimpleModule module) {
        module.setMixInAnnotation(WidgetEvent.class, WidgetEventMixIn.class);
        module.setMixInAnnotation(WidgetEvent.Unrecognized.class, WidgetEventUnrecognizedMixIn.class);
    }

    @JsonTypeInfo(
            use = JsonTypeInfo.Id.NAME,
            include = JsonTypeInfo.As.EXISTING_PROPERTY,
            property = "type",
            visible = true,
            defaultImpl = WidgetEvent.Unrecognized.class
    )
    @JsonSubTypes({
            @JsonSubTypes.Type(value = CreatedEvent.class, name = "widget.created"),
            @JsonSubTypes.Type(value = DeletedEvent.class, name = "widget.deleted")
    })
    interface WidgetEventMixIn {
    }

    abstract static class WidgetEventUnrecognizedMixIn {
        WidgetEventUnrecognizedMixIn(@JsonProperty("type") String type,
                @JsonAnySetter Map<String, Object> properties) {
        }

        @JsonProperty("type")
        abstract String type();

        @JsonAnyGetter
        abstract Map<String, Object> properties();
    }
}
