// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Kindgi Inc.
//
// Generated by kindgi-codegen-maven-plugin from the Kindgi API's openapi.json; do not edit.
package com.kindgi.client.internal.codec;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.kindgi.client.models.WidgetCore;
import com.kindgi.client.models.WidgetState;
import tools.jackson.databind.module.SimpleModule;

/**
 * The client's JSON codec for {@link WidgetCore}.
 */
final class WidgetCoreJson {
    private WidgetCoreJson() {
    }

    static void register(SimpleModule module) {
        module.setMixInAnnotation(WidgetCore.class, WidgetCoreMixIn.class);
    }

    abstract static class WidgetCoreMixIn {
        @JsonProperty("name")
        abstract String name();

        @JsonProperty("state")
        abstract WidgetState state();
    }
}
