// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Kindgi Inc.
//
// Generated by kindgi-codegen-maven-plugin from the Kindgi API's openapi.json; do not edit.
package com.kindgi.client.internal.codec;

import com.kindgi.client.models.WidgetsRotateResponse;
import tools.jackson.databind.module.SimpleModule;

/**
 * The client's JSON codec for {@link WidgetsRotateResponse}.
 */
final class WidgetsRotateResponseJson {
    private WidgetsRotateResponseJson() {
    }

    static void register(SimpleModule module) {
    }
}
