// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Kindgi Inc.
//
// Generated by kindgi-codegen-maven-plugin from the Kindgi API's openapi.json; do not edit.
package com.kindgi.client.internal.codec;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.kindgi.client.models.Widget;
import com.kindgi.client.models.WidgetPage;
import java.util.List;
import tools.jackson.databind.module.SimpleModule;

/**
 * The client's JSON codec for {@link WidgetPage}.
 */
final class WidgetPageJson {
    private WidgetPageJson() {
    }

    static void register(SimpleModule module) {
        module.setMixInAnnotation(WidgetPage.class, WidgetPageMixIn.class);
    }

    abstract static class WidgetPageMixIn {
        @JsonProperty("data")
        abstract List<Widget> data();

        @JsonProperty("hasMore")
        abstract Boolean hasMore();

        @JsonProperty("nextCursor")
        abstract String nextCursor();
    }
}
