// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Kindgi Inc.
//
// Generated by kindgi-codegen-maven-plugin from the Kindgi API's openapi.json; do not edit.
package com.kindgi.client.internal.codec;

import com.fasterxml.jackson.annotation.JsonValue;
import com.kindgi.client.models.PromptRef;
import com.kindgi.client.models.WidgetInstructions;
import tools.jackson.core.JsonParser;
import tools.jackson.core.JsonToken;
import tools.jackson.databind.DeserializationContext;
import tools.jackson.databind.ValueDeserializer;
import tools.jackson.databind.annotation.JsonDeserialize;
import tools.jackson.databind.module.SimpleModule;

/**
 * The client's JSON codec for {@link WidgetInstructions}.
 */
final class WidgetInstructionsJson {
    private WidgetInstructionsJson() {
    }

    static void register(SimpleModule module) {
        module.setMixInAnnotation(WidgetInstructions.Text.class, WidgetInstructionsTextMixIn.class);
        module.setMixInAnnotation(WidgetInstructions.class, WidgetInstructionsMixIn.class);
    }

    /**
     * Reads a {@link WidgetInstructions}: a string is its text, an object one of its object variants.
     */
    static final class WidgetInstructionsCodec extends ValueDeserializer<WidgetInstructions> {
        @Override
        public WidgetInstructions deserialize(JsonParser p, DeserializationContext ctxt) {
            if (p.currentToken() == JsonToken.VALUE_STRING) {
                return new WidgetInstructions.Text(p.getString());
            }
            if (p.currentToken() != JsonToken.START_OBJECT) {
                return (WidgetInstructions) ctxt.handleUnexpectedToken(WidgetInstructions.class, p);
            }
            return ctxt.readValue(p, PromptRef.class);
        }
    }

    abstract static class WidgetInstructionsTextMixIn {
        @JsonValue
        abstract String value();
    }

    @JsonDeserialize(
            using = WidgetInstructionsCodec.class
    )
    interface WidgetInstructionsMixIn {
    }
}
