// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Kindgi Inc.
//
// Generated by kindgi-codegen-maven-plugin from the Kindgi API's openapi.json; do not edit.
package com.kindgi.client.internal.codec;

import com.kindgi.client.models.WidgetState;
import tools.jackson.databind.module.SimpleModule;

/**
 * The client's JSON codec for {@link WidgetState}.
 */
final class WidgetStateJson {
    private WidgetStateJson() {
    }

    static void register(SimpleModule module) {
        TextValues.register(module, WidgetState.class, WidgetState::of, WidgetState::asString);
    }
}
