// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Kindgi Inc.
//
// Generated by kindgi-codegen-maven-plugin from the Kindgi API's openapi.json; do not edit.
package com.kindgi.client.internal;

import java.util.Map;
import java.util.Set;

/**
 * Every operation of the Kindgi API with a client method.
 */
public final class Operations {
    /**
     * {@code widgets.list}: <code>GET /v1/widgets</code>
     */
    public static final Operation WIDGETS_LIST = new Operation("widgets.list", "GET", "/v1/widgets", Operation.Kind.JSON, false);

    /**
     * {@code widgets.create}: <code>POST /v1/widgets</code>
     */
    public static final Operation WIDGETS_CREATE = new Operation("widgets.create", "POST", "/v1/widgets", Operation.Kind.JSON, true);

    /**
     * {@code widgets.get}: <code>GET /v1/widgets/&#123;widgetId&#125;</code>
     */
    public static final Operation WIDGETS_GET = new Operation("widgets.get", "GET", "/v1/widgets/{widgetId}", Operation.Kind.JSON, false);

    /**
     * {@code widgets.update}: <code>PATCH /v1/widgets/&#123;widgetId&#125;</code>
     */
    public static final Operation WIDGETS_UPDATE = new Operation("widgets.update", "PATCH", "/v1/widgets/{widgetId}", Operation.Kind.JSON, false);

    /**
     * {@code widgets.delete}: <code>DELETE /v1/widgets/&#123;widgetId&#125;</code>
     */
    public static final Operation WIDGETS_DELETE = new Operation("widgets.delete", "DELETE", "/v1/widgets/{widgetId}", Operation.Kind.EMPTY, false);

    /**
     * {@code widgets.events.stream}: <code>GET /v1/widgets/&#123;widgetId&#125;/events</code>
     */
    public static final Operation WIDGETS_EVENTS_STREAM = new Operation("widgets.events.stream", "GET", "/v1/widgets/{widgetId}/events", Operation.Kind.SSE, false);

    /**
     * {@code widgets.blob.download}: <code>GET /v1/widgets/&#123;widgetId&#125;/blob</code>
     */
    public static final Operation WIDGETS_BLOB_DOWNLOAD = new Operation("widgets.blob.download", "GET", "/v1/widgets/{widgetId}/blob", Operation.Kind.BINARY, false);

    /**
     * {@code widgets.blob.upload}: <code>POST /v1/widgets/&#123;widgetId&#125;/blob</code>
     */
    public static final Operation WIDGETS_BLOB_UPLOAD = new Operation("widgets.blob.upload", "POST", "/v1/widgets/{widgetId}/blob", Operation.Kind.JSON, false);

    /**
     * {@code widgets.rotate}: <code>POST /v1/widgets/&#123;widgetId&#125;/rotate</code>
     */
    public static final Operation WIDGETS_ROTATE = new Operation("widgets.rotate", "POST", "/v1/widgets/{widgetId}/rotate", Operation.Kind.JSON, false);

    /**
     * {@code settings.put}: <code>PUT /v1/settings/&#123;domain&#125;</code>
     */
    public static final Operation SETTINGS_PUT = new Operation("settings.put", "PUT", "/v1/settings/{domain}", Operation.Kind.JSON, false);

    /**
     * Every operation, by its id.
     */
    public static final Map<String, Operation> ALL = Map.ofEntries(
        Map.entry("widgets.list", WIDGETS_LIST),
        Map.entry("widgets.create", WIDGETS_CREATE),
        Map.entry("widgets.get", WIDGETS_GET),
        Map.entry("widgets.update", WIDGETS_UPDATE),
        Map.entry("widgets.delete", WIDGETS_DELETE),
        Map.entry("widgets.events.stream", WIDGETS_EVENTS_STREAM),
        Map.entry("widgets.blob.download", WIDGETS_BLOB_DOWNLOAD),
        Map.entry("widgets.blob.upload", WIDGETS_BLOB_UPLOAD),
        Map.entry("widgets.rotate", WIDGETS_ROTATE),
        Map.entry("settings.put", SETTINGS_PUT));

    /**
     * The API's operations that have no client method ({@code HEAD}).
     */
    public static final Set<String> WITHOUT_METHOD = Set.of("widgets.head");

    private Operations() {
    }
}
