// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Kindgi Inc.
//
// Generated by kindgi-codegen-maven-plugin from the Kindgi API's openapi.json; do not edit.
package com.kindgi.client.resources;

import com.kindgi.client.KindgiApiException;
import com.kindgi.client.internal.Operations;
import com.kindgi.client.internal.RequestSpec;
import com.kindgi.client.internal.Transport;
import com.kindgi.client.models.WidgetEvent;
import java.util.Objects;
import java.util.UUID;
import java.util.concurrent.Flow;

/**
 * The {@code widgets.events} operations, asynchronously: {@code client.widgets().events()}.
 */
public final class AsyncWidgetsEventsResource {
    private final Transport transport;

    /**
     * For the client; you get a resource from it.
     *
     * @param transport the client's transport
     */
    public AsyncWidgetsEventsResource(Transport transport) {
        this.transport = transport;
    }

    /**
     * Follow a widget.
     *
     * <p><code>GET /v1/widgets/&#123;widgetId&#125;/events</code> ({@code widgets.events.stream})
     *
     * @param widgetId The widgetId.
     * @param params the query and header parameters
     * @return the events, as they come; the stream resumes after a dropped connection
     * @throws KindgiApiException when the API refuses the call or can't be reached
     */
    public Flow.Publisher<WidgetEvent> stream(UUID widgetId, WidgetsEventsStreamParams params) {
        Objects.requireNonNull(widgetId, "widgetId");
        Objects.requireNonNull(params, "params");
        params.validate();
        RequestSpec request = RequestSpec.of(Operations.WIDGETS_EVENTS_STREAM)
                .path("widgetId", widgetId)
                .header("Last-Event-Id", params.lastEventId());
        return transport.streamAsync(request, WidgetEvent.class);
    }

    /**
     * Follow a widget.
     *
     * <p><code>GET /v1/widgets/&#123;widgetId&#125;/events</code> ({@code widgets.events.stream})
     *
     * @param widgetId The widgetId.
     * @return the events, as they come; the stream resumes after a dropped connection
     * @throws KindgiApiException when the API refuses the call or can't be reached
     */
    public Flow.Publisher<WidgetEvent> stream(UUID widgetId) {
        return stream(widgetId, WidgetsEventsStreamParams.builder().build());
    }
}
