// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Kindgi Inc.
//
// Generated by kindgi-codegen-maven-plugin from the Kindgi API's openapi.json; do not edit.
package com.kindgi.client.resources;

import com.kindgi.client.KindgiApiException;
import com.kindgi.client.internal.Multipart;
import com.kindgi.client.internal.Operations;
import com.kindgi.client.internal.RequestSpec;
import com.kindgi.client.internal.Transport;
import com.kindgi.client.models.UploadBody;
import com.kindgi.client.models.Widget;
import java.util.Objects;
import java.util.UUID;
import java.util.concurrent.CompletableFuture;

/**
 * The {@code widgets.blob} operations, asynchronously: {@code client.widgets().blob()}.
 */
public final class AsyncWidgetsBlobResource {
    private final Transport transport;

    /**
     * For the client; you get a resource from it.
     *
     * @param transport the client's transport
     */
    public AsyncWidgetsBlobResource(Transport transport) {
        this.transport = transport;
    }

    /**
     * Download its bytes.
     *
     * <p><code>GET /v1/widgets/&#123;widgetId&#125;/blob</code> ({@code widgets.blob.download})
     *
     * @param widgetId The widgetId.
     * @return the bytes
     * @throws KindgiApiException when the API refuses the call or can't be reached
     */
    public CompletableFuture<byte[]> download(UUID widgetId) {
        Objects.requireNonNull(widgetId, "widgetId");
        RequestSpec request = RequestSpec.of(Operations.WIDGETS_BLOB_DOWNLOAD)
                .path("widgetId", widgetId);
        return transport.binaryAsync(request);
    }

    /**
     * Upload its bytes.
     *
     * <p><code>POST /v1/widgets/&#123;widgetId&#125;/blob</code> ({@code widgets.blob.upload})
     *
     * @param widgetId The widgetId.
     * @param body the request body
     * @return the answer
     * @throws KindgiApiException when the API refuses the call or can't be reached
     */
    public CompletableFuture<Widget> upload(UUID widgetId, UploadBody body) {
        Objects.requireNonNull(widgetId, "widgetId");
        Objects.requireNonNull(body, "body");
        RequestSpec request = RequestSpec.of(Operations.WIDGETS_BLOB_UPLOAD)
                .path("widgetId", widgetId)
                .multipart(body == null ? null : new Multipart().file("file", body.file()).text("name", body.name()).text("ownerId", body.ownerId()));
        return transport.jsonAsync(request, Widget.class);
    }
}
