// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Kindgi Inc.
//
// Generated by kindgi-codegen-maven-plugin from the Kindgi API's openapi.json; do not edit.
package com.kindgi.client.resources;

import com.kindgi.client.KindgiApiException;
import com.kindgi.client.internal.Operations;
import com.kindgi.client.internal.RequestSpec;
import com.kindgi.client.internal.Transport;
import com.kindgi.client.models.CreateWidgetBody;
import com.kindgi.client.models.PatchWidgetBody;
import com.kindgi.client.models.RotateDone;
import com.kindgi.client.models.RotateQueued;
import com.kindgi.client.models.Widget;
import com.kindgi.client.models.WidgetPage;
import com.kindgi.client.models.WidgetsRotateResponse;
import java.util.Map;
import java.util.Objects;
import java.util.UUID;
import java.util.concurrent.CompletableFuture;
import org.jspecify.annotations.Nullable;

/**
 * The {@code widgets} operations, asynchronously: {@code client.widgets()}.
 */
public final class AsyncWidgetsResource {
    private final Transport transport;

    private final AsyncWidgetsEventsResource events;

    private final AsyncWidgetsBlobResource blob;

    /**
     * For the client; you get a resource from it.
     *
     * @param transport the client's transport
     */
    public AsyncWidgetsResource(Transport transport) {
        this.transport = transport;
        this.events = new AsyncWidgetsEventsResource(transport);
        this.blob = new AsyncWidgetsBlobResource(transport);
    }

    /**
     * The {@code widgets.events} operations.
     *
     * @return the resource
     */
    public AsyncWidgetsEventsResource events() {
        return events;
    }

    /**
     * The {@code widgets.blob} operations.
     *
     * @return the resource
     */
    public AsyncWidgetsBlobResource blob() {
        return blob;
    }

    /**
     * List widgets.
     *
     * <p><code>GET /v1/widgets</code> ({@code widgets.list})
     *
     * <p>Cursor-paginated.
     *
     * @param params the query and header parameters
     * @return the answer
     * @throws KindgiApiException when the API refuses the call or can't be reached
     */
    public CompletableFuture<WidgetPage> list(WidgetsListParams params) {
        Objects.requireNonNull(params, "params");
        params.validate();
        RequestSpec request = RequestSpec.of(Operations.WIDGETS_LIST)
                .query("cursor", params.cursor())
                .query("limit", params.limit())
                .query("state", params.state())
                .query("order", params.order())
                .query("segment", params.segments() == null ? null : params.segments().stream().map(step -> step.key() + ":" + step.value()).toList())
                .query("since", params.since())
                .query("archived", params.archived());
        return transport.jsonAsync(request, WidgetPage.class);
    }

    /**
     * List widgets.
     *
     * <p><code>GET /v1/widgets</code> ({@code widgets.list})
     *
     * <p>Cursor-paginated.
     *
     * @return the answer
     * @throws KindgiApiException when the API refuses the call or can't be reached
     */
    public CompletableFuture<WidgetPage> list() {
        return list(WidgetsListParams.builder().build());
    }

    /**
     * Create a widget.
     *
     * <p><code>POST /v1/widgets</code> ({@code widgets.create})
     *
     * @param body the request body
     * @param params the query and header parameters
     * @return the answer
     * @throws KindgiApiException when the API refuses the call or can't be reached
     */
    public CompletableFuture<Widget> create(CreateWidgetBody body, WidgetsCreateParams params) {
        Objects.requireNonNull(body, "body");
        Objects.requireNonNull(params, "params");
        params.validate();
        RequestSpec request = RequestSpec.of(Operations.WIDGETS_CREATE)
                .header("Idempotency-Key", params.idempotencyKey())
                .json(body);
        return transport.jsonAsync(request, Widget.class);
    }

    /**
     * Create a widget.
     *
     * <p><code>POST /v1/widgets</code> ({@code widgets.create})
     *
     * @param body the request body
     * @return the answer
     * @throws KindgiApiException when the API refuses the call or can't be reached
     */
    public CompletableFuture<Widget> create(CreateWidgetBody body) {
        return create(body, WidgetsCreateParams.builder().build());
    }

    /**
     * Fetch a widget.
     *
     * <p><code>GET /v1/widgets/&#123;widgetId&#125;</code> ({@code widgets.get})
     *
     * @param widgetId The widgetId.
     * @return the answer
     * @throws KindgiApiException when the API refuses the call or can't be reached
     */
    public CompletableFuture<Widget> get(UUID widgetId) {
        Objects.requireNonNull(widgetId, "widgetId");
        RequestSpec request = RequestSpec.of(Operations.WIDGETS_GET)
                .path("widgetId", widgetId);
        return transport.jsonAsync(request, Widget.class);
    }

    /**
     * Update a widget.
     *
     * <p><code>PATCH /v1/widgets/&#123;widgetId&#125;</code> ({@code widgets.update})
     *
     * @param widgetId The widgetId.
     * @param body the request body
     * @return the answer
     * @throws KindgiApiException when the API refuses the call or can't be reached
     */
    public CompletableFuture<Widget> update(UUID widgetId, PatchWidgetBody body) {
        Objects.requireNonNull(widgetId, "widgetId");
        Objects.requireNonNull(body, "body");
        RequestSpec request = RequestSpec.of(Operations.WIDGETS_UPDATE)
                .path("widgetId", widgetId)
                .json(body);
        return transport.jsonAsync(request, Widget.class);
    }

    /**
     * Delete a widget.
     *
     * <p><code>DELETE /v1/widgets/&#123;widgetId&#125;</code> ({@code widgets.delete})
     *
     * @param widgetId The widgetId.
     * @throws KindgiApiException when the API refuses the call or can't be reached
     */
    public CompletableFuture<Void> delete(UUID widgetId) {
        Objects.requireNonNull(widgetId, "widgetId");
        RequestSpec request = RequestSpec.of(Operations.WIDGETS_DELETE)
                .path("widgetId", widgetId);
        return transport.emptyAsync(request);
    }

    /**
     * Rotate a widget.
     *
     * <p><code>POST /v1/widgets/&#123;widgetId&#125;/rotate</code> ({@code widgets.rotate})
     *
     * @param widgetId The widgetId.
     * @param body the request body
     * @return the answer
     * @throws KindgiApiException when the API refuses the call or can't be reached
     */
    public CompletableFuture<WidgetsRotateResponse> rotate(UUID widgetId,
            @Nullable Map<String, Object> body) {
        Objects.requireNonNull(widgetId, "widgetId");
        RequestSpec request = RequestSpec.of(Operations.WIDGETS_ROTATE)
                .path("widgetId", widgetId)
                .json(body);
        return transport.byStatusAsync(request, WidgetsRotateResponse.class, Map.of(201, RotateDone.class, 202, RotateQueued.class));
    }

    /**
     * Rotate a widget.
     *
     * <p><code>POST /v1/widgets/&#123;widgetId&#125;/rotate</code> ({@code widgets.rotate})
     *
     * @param widgetId The widgetId.
     * @return the answer
     * @throws KindgiApiException when the API refuses the call or can't be reached
     */
    public CompletableFuture<WidgetsRotateResponse> rotate(UUID widgetId) {
        return rotate(widgetId, null);
    }
}
