// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Kindgi Inc.
//
// Generated by kindgi-codegen-maven-plugin from the Kindgi API's openapi.json; do not edit.
package com.kindgi.client.resources;

import com.kindgi.client.KindgiApiException;
import com.kindgi.client.internal.Operations;
import com.kindgi.client.internal.RequestSpec;
import com.kindgi.client.internal.Transport;
import com.kindgi.client.models.SettingsPutBody;
import com.kindgi.client.models.SettingsPutDomain;
import com.kindgi.client.models.SettingsPutResponse;
import java.util.Objects;

/**
 * The {@code settings} operations: {@code client.settings()}.
 */
public final class SettingsResource {
    private final Transport transport;

    /**
     * For the client; you get a resource from it.
     *
     * @param transport the client's transport
     */
    public SettingsResource(Transport transport) {
        this.transport = transport;
    }

    /**
     * Set the settings.
     *
     * <p><code>PUT /v1/settings/&#123;domain&#125;</code> ({@code settings.put})
     *
     * @param domain the {@code domain}
     * @param body the request body
     * @param params the query and header parameters
     * @return the answer
     * @throws KindgiApiException when the API refuses the call or can't be reached
     */
    public SettingsPutResponse put(SettingsPutDomain domain, SettingsPutBody body,
            SettingsPutParams params) {
        Objects.requireNonNull(domain, "domain");
        Objects.requireNonNull(body, "body");
        Objects.requireNonNull(params, "params");
        params.validate();
        RequestSpec request = RequestSpec.of(Operations.SETTINGS_PUT)
                .path("domain", domain)
                .header("X-Supervisor-Id", params.supervisorId())
                .json(body);
        return transport.json(request, SettingsPutResponse.class);
    }
}
