// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Kindgi Inc.
//
// Generated by kindgi-codegen-maven-plugin from the Kindgi API's openapi.json; do not edit.
package com.kindgi.client.resources;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.kindgi.client.models.Checks;
import com.kindgi.client.models.Model;
import com.kindgi.client.models.ValidationException;

/**
 * The query and header parameters of &#123;&#64;code settings.put&#125;.
 *
 * @param supervisorId Required.
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public record SettingsPutParams(
        @JsonProperty("X-Supervisor-Id") String supervisorId) implements Model {
    public SettingsPutParams {
        supervisorId = Checks.required(supervisorId, "SettingsPutParams.X-Supervisor-Id");
    }

    @Override
    public void validate(Checks checks) {
    }

    /**
     * A builder for a {@link SettingsPutParams}.
     *
     * @return the builder
     */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * A builder that starts from this value.
     *
     * @return the builder
     */
    public Builder toBuilder() {
        return new Builder(this);
    }

    /**
     * Builds a {@link SettingsPutParams}; {@link #build()} checks it against the API's constraints.
     */
    public static final class Builder {
        private String supervisorId;

        private Builder() {
        }

        private Builder(SettingsPutParams source) {
            this.supervisorId = source.supervisorId;
        }

        /**
         * Required.
         */
        public Builder supervisorId(String supervisorId) {
            this.supervisorId = supervisorId;
            return this;
        }

        /**
         * The {@link SettingsPutParams}.
         *
         * @return the value
         * @throws ValidationException when it breaks the API's constraints (every problem is listed)
         */
        public SettingsPutParams build() {
            SettingsPutParams built = new SettingsPutParams(supervisorId);
            built.validate();
            return built;
        }
    }
}
