// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Kindgi Inc.
//
// Generated by kindgi-codegen-maven-plugin from the Kindgi API's openapi.json; do not edit.
package com.kindgi.client.resources;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import com.kindgi.client.models.Checks;
import com.kindgi.client.models.Model;
import com.kindgi.client.models.ScopeSegment;
import com.kindgi.client.models.ValidationException;
import com.kindgi.client.models.WidgetState;
import java.time.OffsetDateTime;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.jspecify.annotations.Nullable;

/**
 * The query and header parameters of &#123;&#64;code widgets.list&#125;.
 *
 * @param cursor Where to start.
 * @param segments One step, <code>key:value</code>.
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public record WidgetsListParams(@JsonProperty("cursor") @Nullable String cursor,
        @JsonProperty("limit") @Nullable Long limit,
        @JsonProperty("state") @Nullable WidgetState state,
        @JsonProperty("order") WidgetsListParams. @Nullable Order order,
        @JsonProperty("segment") @Nullable List<ScopeSegment> segments,
        @JsonProperty("since") @Nullable OffsetDateTime since,
        @JsonProperty("archived") @Nullable Boolean archived) implements Model {
    public WidgetsListParams {
        segments = Checks.list(segments);
    }

    @Override
    public void validate(Checks checks) {
        checks.minimum("limit", limit, "1");
        checks.maximum("limit", limit, "100");
        checks.nested("segment", segments);
    }

    /**
     * A builder for a {@link WidgetsListParams}.
     *
     * @return the builder
     */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * A builder that starts from this value.
     *
     * @return the builder
     */
    public Builder toBuilder() {
        return new Builder(this);
    }

    /**
     * Builds a {@link WidgetsListParams}; {@link #build()} checks it against the API's constraints.
     */
    public static final class Builder {
        private @Nullable String cursor;

        private @Nullable Long limit;

        private @Nullable WidgetState state;

        private @Nullable Order order;

        private @Nullable List<ScopeSegment> segments;

        private @Nullable OffsetDateTime since;

        private @Nullable Boolean archived;

        private Builder() {
        }

        private Builder(WidgetsListParams source) {
            this.cursor = source.cursor;
            this.limit = source.limit;
            this.state = source.state;
            this.order = source.order;
            this.segments = source.segments;
            this.since = source.since;
            this.archived = source.archived;
        }

        /**
         * Where to start.
         */
        public Builder cursor(@Nullable String cursor) {
            this.cursor = cursor;
            return this;
        }

        public Builder limit(@Nullable Long limit) {
            this.limit = limit;
            return this;
        }

        public Builder state(@Nullable WidgetState state) {
            this.state = state;
            return this;
        }

        public Builder order(@Nullable Order order) {
            this.order = order;
            return this;
        }

        /**
         * One step, <code>key:value</code>.
         */
        public Builder segments(@Nullable List<ScopeSegment> segments) {
            this.segments = segments;
            return this;
        }

        public Builder since(@Nullable OffsetDateTime since) {
            this.since = since;
            return this;
        }

        public Builder archived(@Nullable Boolean archived) {
            this.archived = archived;
            return this;
        }

        /**
         * The {@link WidgetsListParams}.
         *
         * @return the value
         * @throws ValidationException when it breaks the API's constraints (every problem is listed)
         */
        public WidgetsListParams build() {
            WidgetsListParams built = new WidgetsListParams(cursor, limit, state, order, segments, since, archived);
            built.validate();
            return built;
        }
    }

    /**
     * One of the values below, or one this client doesn't know yet: {@link #of} keeps any value, and {@link #value()} is {@code UNRECOGNIZED} for an unknown one. Switch on {@link #value()}.
     */
    public static final class Order {
        /**
         * <code>asc</code>
         */
        public static final Order ASC = new Order("asc", Value.ASC);

        /**
         * <code>desc</code>
         */
        public static final Order DESC = new Order("desc", Value.DESC);

        private static final Map<String, Order> byValue = Map.ofEntries(
            Map.entry("asc", ASC),
            Map.entry("desc", DESC));

        private final String raw;

        private final Value value;

        private Order(String raw, Value value) {
            this.raw = raw;
            this.value = value;
        }

        /**
         * The value for this text: a known constant, or an unrecognized value that keeps it.
         */
        @JsonCreator
        public static Order of(String raw) {
            Order known = byValue.get(Objects.requireNonNull(raw, "raw"));
            return known != null ? known : new Order(raw, Value.UNRECOGNIZED);
        }

        /**
         * The value as the API spells it.
         */
        @JsonValue
        public String asString() {
            return raw;
        }

        /**
         * Which known value this is, or {@code UNRECOGNIZED}.
         */
        public Value value() {
            return value;
        }

        /**
         * Whether this client knows the value.
         */
        public boolean isKnown() {
            return value != Value.UNRECOGNIZED;
        }

        @Override
        public boolean equals(Object other) {
            return other instanceof Order && ((Order) other).raw.equals(raw);
        }

        @Override
        public int hashCode() {
            return raw.hashCode();
        }

        @Override
        public String toString() {
            return raw;
        }

        /**
         * The values this client knows, and {@code UNRECOGNIZED}.
         */
        public enum Value {
            ASC,

            DESC,

            UNRECOGNIZED
        }
    }
}
