// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Kindgi Inc.
//
// Generated by kindgi-codegen-maven-plugin from the Kindgi API's openapi.json; do not edit.
package com.kindgi.client.resources;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.kindgi.client.models.Checks;
import com.kindgi.client.models.Model;
import com.kindgi.client.models.ValidationException;
import org.jspecify.annotations.Nullable;

/**
 * The query and header parameters of &#123;&#64;code widgets.create&#125;.
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public record WidgetsCreateParams(
        @JsonProperty("Idempotency-Key") @Nullable String idempotencyKey) implements Model {
    @Override
    public void validate(Checks checks) {
        checks.minLength("Idempotency-Key", idempotencyKey, 1);
        checks.maxLength("Idempotency-Key", idempotencyKey, 255);
    }

    /**
     * A builder for a {@link WidgetsCreateParams}.
     *
     * @return the builder
     */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * A builder that starts from this value.
     *
     * @return the builder
     */
    public Builder toBuilder() {
        return new Builder(this);
    }

    /**
     * Builds a {@link WidgetsCreateParams}; {@link #build()} checks it against the API's constraints.
     */
    public static final class Builder {
        private @Nullable String idempotencyKey;

        private Builder() {
        }

        private Builder(WidgetsCreateParams source) {
            this.idempotencyKey = source.idempotencyKey;
        }

        public Builder idempotencyKey(@Nullable String idempotencyKey) {
            this.idempotencyKey = idempotencyKey;
            return this;
        }

        /**
         * The {@link WidgetsCreateParams}.
         *
         * @return the value
         * @throws ValidationException when it breaks the API's constraints (every problem is listed)
         */
        public WidgetsCreateParams build() {
            WidgetsCreateParams built = new WidgetsCreateParams(idempotencyKey);
            built.validate();
            return built;
        }
    }
}
