// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Kindgi Inc.
//
// Generated by kindgi-codegen-maven-plugin from the Kindgi API's openapi.json; do not edit.
package com.kindgi.client.resources;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.kindgi.client.models.Checks;
import com.kindgi.client.models.Model;
import com.kindgi.client.models.ValidationException;
import org.jspecify.annotations.Nullable;

/**
 * The query and header parameters of &#123;&#64;code widgets.events.stream&#125;.
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public record WidgetsEventsStreamParams(
        @JsonProperty("Last-Event-Id") @Nullable String lastEventId) implements Model {
    @Override
    public void validate(Checks checks) {
    }

    /**
     * A builder for a {@link WidgetsEventsStreamParams}.
     *
     * @return the builder
     */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * A builder that starts from this value.
     *
     * @return the builder
     */
    public Builder toBuilder() {
        return new Builder(this);
    }

    /**
     * Builds a {@link WidgetsEventsStreamParams}; {@link #build()} checks it against the API's constraints.
     */
    public static final class Builder {
        private @Nullable String lastEventId;

        private Builder() {
        }

        private Builder(WidgetsEventsStreamParams source) {
            this.lastEventId = source.lastEventId;
        }

        public Builder lastEventId(@Nullable String lastEventId) {
            this.lastEventId = lastEventId;
            return this;
        }

        /**
         * The {@link WidgetsEventsStreamParams}.
         *
         * @return the value
         * @throws ValidationException when it breaks the API's constraints (every problem is listed)
         */
        public WidgetsEventsStreamParams build() {
            WidgetsEventsStreamParams built = new WidgetsEventsStreamParams(lastEventId);
            built.validate();
            return built;
        }
    }
}
