// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Kindgi Inc.
//
// Generated by kindgi-codegen-maven-plugin from the Kindgi API's openapi.json; do not edit.
package com.kindgi.client.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.jspecify.annotations.Nullable;

/**
 * One of:
 * <ul>
 * <li>{@link Baseline.WithAgentId}: has {@code agentId}</li>
 * <li>{@link Baseline.WithLive}: has {@code live}</li>
 * <li>{@link Baseline.Recorded}: text, <code>recorded</code></li>
 * <li>{@link Unrecognized}: a variant this client doesn't know yet, kept as it came</li>
 * </ul>
 */
public sealed interface Baseline extends Model permits Baseline.WithAgentId, Baseline.WithLive, Baseline.Recorded, Baseline.Unrecognized {
    /**
     * <code>recorded</code>
     */
    Recorded RECORDED = new Recorded("recorded");

    /**
     * The text variant.
     */
    static Baseline of(String text) {
        return new Recorded(text);
    }

    /**
     * A variant this client doesn't know yet (a newer runtime's), kept as it came.
     *
     * @param properties its other properties
     */
    @JsonInclude(JsonInclude.Include.NON_NULL)
    record Unrecognized(
            @JsonAnySetter @JsonAnyGetter Map<String, Object> properties) implements Baseline {
        public Unrecognized {
            properties = Checks.extras(properties);
        }

        @Override
        public void validate(Checks checks) {
            // Nothing to check: the client doesn't know this variant's constraints.
        }
    }

    /**
     * The text variant.
     *
     * @param value the text
     */
    record Recorded(@JsonValue String value) implements Baseline {
        public Recorded {
            Objects.requireNonNull(value, "Baseline text");
        }

        @Override
        public void validate(Checks checks) {
            checks.oneOf("", value, List.of("recorded"));
        }
    }

    /**
     * @param agentId Required.
     * @param version Required.
     */
    @JsonInclude(JsonInclude.Include.NON_NULL)
    record WithAgentId(@JsonProperty("agentId") String agentId,
            @JsonProperty("version") String version) implements Baseline {
        public WithAgentId {
            agentId = Checks.required(agentId, "Baseline.WithAgentId.agentId");
            version = Checks.required(version, "Baseline.WithAgentId.version");
        }

        @Override
        public void validate(Checks checks) {
        }

        /**
         * A builder for a {@link WithAgentId}.
         *
         * @return the builder
         */
        public static Builder builder() {
            return new Builder();
        }

        /**
         * A builder that starts from this value.
         *
         * @return the builder
         */
        public Builder toBuilder() {
            return new Builder(this);
        }

        /**
         * Builds a {@link WithAgentId}; {@link #build()} checks it against the API's constraints.
         */
        public static final class Builder {
            private String agentId;

            private String version;

            private Builder() {
            }

            private Builder(WithAgentId source) {
                this.agentId = source.agentId;
                this.version = source.version;
            }

            /**
             * Required.
             */
            public Builder agentId(String agentId) {
                this.agentId = agentId;
                return this;
            }

            /**
             * Required.
             */
            public Builder version(String version) {
                this.version = version;
                return this;
            }

            /**
             * The {@link WithAgentId}.
             *
             * @return the value
             * @throws ValidationException when it breaks the API's constraints (every problem is listed)
             */
            public WithAgentId build() {
                WithAgentId built = new WithAgentId(agentId, version);
                built.validate();
                return built;
            }
        }
    }

    /**
     * @param live Required.
     */
    @JsonInclude(JsonInclude.Include.NON_NULL)
    record WithLive(@JsonProperty("live") WithLive.Live live) implements Baseline {
        public WithLive {
            live = Checks.required(live, "Baseline.WithLive.live");
        }

        @Override
        public void validate(Checks checks) {
            checks.nested("live", live);
        }

        /**
         * A builder for a {@link WithLive}.
         *
         * @return the builder
         */
        public static Builder builder() {
            return new Builder();
        }

        /**
         * A builder that starts from this value.
         *
         * @return the builder
         */
        public Builder toBuilder() {
            return new Builder(this);
        }

        /**
         * Builds a {@link WithLive}; {@link #build()} checks it against the API's constraints.
         */
        public static final class Builder {
            private Live live;

            private Builder() {
            }

            private Builder(WithLive source) {
                this.live = source.live;
            }

            /**
             * Required.
             */
            public Builder live(Live live) {
                this.live = live;
                return this;
            }

            /**
             * The {@link WithLive}.
             *
             * @return the value
             * @throws ValidationException when it breaks the API's constraints (every problem is listed)
             */
            public WithLive build() {
                WithLive built = new WithLive(live);
                built.validate();
                return built;
            }
        }

        @JsonInclude(JsonInclude.Include.NON_NULL)
        public static record Live(
                @JsonProperty("projectId") @Nullable String projectId) implements Model {
            @Override
            public void validate(Checks checks) {
            }

            /**
             * A builder for a {@link Live}.
             *
             * @return the builder
             */
            public static Builder builder() {
                return new Builder();
            }

            /**
             * A builder that starts from this value.
             *
             * @return the builder
             */
            public Builder toBuilder() {
                return new Builder(this);
            }

            /**
             * Builds a {@link Live}; {@link #build()} checks it against the API's constraints.
             */
            public static final class Builder {
                private @Nullable String projectId;

                private Builder() {
                }

                private Builder(Live source) {
                    this.projectId = source.projectId;
                }

                public Builder projectId(@Nullable String projectId) {
                    this.projectId = projectId;
                    return this;
                }

                /**
                 * The {@link Live}.
                 *
                 * @return the value
                 * @throws ValidationException when it breaks the API's constraints (every problem is listed)
                 */
                public Live build() {
                    Live built = new Live(projectId);
                    built.validate();
                    return built;
                }
            }
        }
    }
}
