// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Kindgi Inc.
//
// Generated by kindgi-codegen-maven-plugin from the Kindgi API's openapi.json; do not edit.
package com.kindgi.client.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * @param radius Required.
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public record Circle(@JsonProperty("kind") String kind,
        @JsonProperty("radius") Double radius) implements Shape {
    public Circle {
        kind = Checks.constant(kind, "circle", "Circle.kind");
        radius = Checks.required(radius, "Circle.radius");
    }

    @Override
    public void validate(Checks checks) {
        checks.minimum("radius", radius, "0");
    }

    /**
     * A builder for a {@link Circle}.
     *
     * @return the builder
     */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * A builder that starts from this value.
     *
     * @return the builder
     */
    public Builder toBuilder() {
        return new Builder(this);
    }

    /**
     * Builds a {@link Circle}; {@link #build()} checks it against the API's constraints.
     */
    public static final class Builder {
        private String kind = "circle";

        private Double radius;

        private Builder() {
        }

        private Builder(Circle source) {
            this.kind = source.kind;
            this.radius = source.radius;
        }

        /**
         * Required.
         */
        public Builder radius(Double radius) {
            this.radius = radius;
            return this;
        }

        /**
         * The {@link Circle}.
         *
         * @return the value
         * @throws ValidationException when it breaks the API's constraints (every problem is listed)
         */
        public Circle build() {
            Circle built = new Circle(kind, radius);
            built.validate();
            return built;
        }
    }
}
