// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Kindgi Inc.
//
// Generated by kindgi-codegen-maven-plugin from the Kindgi API's openapi.json; do not edit.
package com.kindgi.client.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import java.util.Map;

/**
 * One of:
 * <ul>
 * <li>{@link Content.WithText}: has {@code text}</li>
 * <li>{@link Content.WithValues}: has {@code values}</li>
 * <li>{@link Unrecognized}: a variant this client doesn't know yet, kept as it came</li>
 * </ul>
 */
@JsonTypeInfo(
        use = JsonTypeInfo.Id.DEDUCTION,
        defaultImpl = Content.Unrecognized.class
)
@JsonSubTypes({
        @JsonSubTypes.Type(Content.WithText.class),
        @JsonSubTypes.Type(Content.WithValues.class)
})
public sealed interface Content extends Model permits Content.WithText, Content.WithValues, Content.Unrecognized {
    /**
     * A variant this client doesn't know yet (a newer runtime's), kept as it came.
     *
     * @param properties its other properties
     */
    @JsonInclude(JsonInclude.Include.NON_NULL)
    record Unrecognized(
            @JsonAnySetter @JsonAnyGetter Map<String, Object> properties) implements Content {
        public Unrecognized {
            properties = Checks.extras(properties);
        }

        @Override
        public void validate(Checks checks) {
            // Nothing to check: the client doesn't know this variant's constraints.
        }
    }

    /**
     * @param text Required.
     */
    @JsonInclude(JsonInclude.Include.NON_NULL)
    record WithText(@JsonProperty("text") String text) implements Content {
        public WithText {
            text = Checks.required(text, "Content.WithText.text");
        }

        @Override
        public void validate(Checks checks) {
        }

        /**
         * A builder for a {@link WithText}.
         *
         * @return the builder
         */
        public static Builder builder() {
            return new Builder();
        }

        /**
         * A builder that starts from this value.
         *
         * @return the builder
         */
        public Builder toBuilder() {
            return new Builder(this);
        }

        /**
         * Builds a {@link WithText}; {@link #build()} checks it against the API's constraints.
         */
        public static final class Builder {
            private String text;

            private Builder() {
            }

            private Builder(WithText source) {
                this.text = source.text;
            }

            /**
             * Required.
             */
            public Builder text(String text) {
                this.text = text;
                return this;
            }

            /**
             * The {@link WithText}.
             *
             * @return the value
             * @throws ValidationException when it breaks the API's constraints (every problem is listed)
             */
            public WithText build() {
                WithText built = new WithText(text);
                built.validate();
                return built;
            }
        }
    }

    /**
     * @param values Required.
     */
    @JsonInclude(JsonInclude.Include.NON_NULL)
    record WithValues(@JsonProperty("values") Map<String, Object> values) implements Content {
        public WithValues {
            values = Checks.required(values, "Content.WithValues.values");
            values = Checks.map(values);
        }

        @Override
        public void validate(Checks checks) {
        }

        /**
         * A builder for a {@link WithValues}.
         *
         * @return the builder
         */
        public static Builder builder() {
            return new Builder();
        }

        /**
         * A builder that starts from this value.
         *
         * @return the builder
         */
        public Builder toBuilder() {
            return new Builder(this);
        }

        /**
         * Builds a {@link WithValues}; {@link #build()} checks it against the API's constraints.
         */
        public static final class Builder {
            private Map<String, Object> values;

            private Builder() {
            }

            private Builder(WithValues source) {
                this.values = source.values;
            }

            /**
             * Required.
             */
            public Builder values(Map<String, Object> values) {
                this.values = values;
                return this;
            }

            /**
             * The {@link WithValues}.
             *
             * @return the value
             * @throws ValidationException when it breaks the API's constraints (every problem is listed)
             */
            public WithValues build() {
                WithValues built = new WithValues(values);
                built.validate();
                return built;
            }
        }
    }
}
