// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Kindgi Inc.
//
// Generated by kindgi-codegen-maven-plugin from the Kindgi API's openapi.json; do not edit.
package com.kindgi.client.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * @param widget Required.
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public record CreatedEvent(@JsonProperty("type") String type,
        @JsonProperty("widget") Widget widget) implements WidgetEvent {
    public CreatedEvent {
        type = Checks.constant(type, "widget.created", "CreatedEvent.type");
        widget = Checks.required(widget, "CreatedEvent.widget");
    }

    @Override
    public void validate(Checks checks) {
        checks.nested("widget", widget);
    }

    /**
     * A builder for a {@link CreatedEvent}.
     *
     * @return the builder
     */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * A builder that starts from this value.
     *
     * @return the builder
     */
    public Builder toBuilder() {
        return new Builder(this);
    }

    /**
     * Builds a {@link CreatedEvent}; {@link #build()} checks it against the API's constraints.
     */
    public static final class Builder {
        private String type = "widget.created";

        private Widget widget;

        private Builder() {
        }

        private Builder(CreatedEvent source) {
            this.type = source.type;
            this.widget = source.widget;
        }

        /**
         * Required.
         */
        public Builder widget(Widget widget) {
            this.widget = widget;
            return this;
        }

        /**
         * The {@link CreatedEvent}.
         *
         * @return the value
         * @throws ValidationException when it breaks the API's constraints (every problem is listed)
         */
        public CreatedEvent build() {
            CreatedEvent built = new CreatedEvent(type, widget);
            built.validate();
            return built;
        }
    }
}
