// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Kindgi Inc.
//
// Generated by kindgi-codegen-maven-plugin from the Kindgi API's openapi.json; do not edit.
package com.kindgi.client.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

/**
 * @param name Required.
 * @param shape Required.
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public record CreateWidgetBody(@JsonProperty("name") String name,
        @JsonProperty("state") @Nullable WidgetState state,
        @JsonProperty("shape") Shape shape) implements Model {
    public CreateWidgetBody {
        name = Checks.required(name, "CreateWidgetBody.name");
        shape = Checks.required(shape, "CreateWidgetBody.shape");
    }

    @Override
    public void validate(Checks checks) {
        checks.minLength("name", name, 1);
        checks.nested("shape", shape);
    }

    /**
     * A builder for a {@link CreateWidgetBody}.
     *
     * @return the builder
     */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * A builder that starts from this value.
     *
     * @return the builder
     */
    public Builder toBuilder() {
        return new Builder(this);
    }

    /**
     * Builds a {@link CreateWidgetBody}; {@link #build()} checks it against the API's constraints.
     */
    public static final class Builder {
        private String name;

        private @Nullable WidgetState state;

        private Shape shape;

        private Builder() {
        }

        private Builder(CreateWidgetBody source) {
            this.name = source.name;
            this.state = source.state;
            this.shape = source.shape;
        }

        /**
         * Required.
         */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        public Builder state(@Nullable WidgetState state) {
            this.state = state;
            return this;
        }

        /**
         * Required.
         */
        public Builder shape(Shape shape) {
            this.shape = shape;
            return this;
        }

        /**
         * The {@link CreateWidgetBody}.
         *
         * @return the value
         * @throws ValidationException when it breaks the API's constraints (every problem is listed)
         */
        public CreateWidgetBody build() {
            CreateWidgetBody built = new CreateWidgetBody(name, state, shape);
            built.validate();
            return built;
        }
    }
}
