// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Kindgi Inc.
//
// Generated by kindgi-codegen-maven-plugin from the Kindgi API's openapi.json; do not edit.
package com.kindgi.client.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.UUID;

/**
 * @param widgetId Required.
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public record DeletedEvent(@JsonProperty("type") String type,
        @JsonProperty("widgetId") UUID widgetId) implements WidgetEvent {
    public DeletedEvent {
        type = Checks.constant(type, "widget.deleted", "DeletedEvent.type");
        widgetId = Checks.required(widgetId, "DeletedEvent.widgetId");
    }

    @Override
    public void validate(Checks checks) {
    }

    /**
     * A builder for a {@link DeletedEvent}.
     *
     * @return the builder
     */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * A builder that starts from this value.
     *
     * @return the builder
     */
    public Builder toBuilder() {
        return new Builder(this);
    }

    /**
     * Builds a {@link DeletedEvent}; {@link #build()} checks it against the API's constraints.
     */
    public static final class Builder {
        private String type = "widget.deleted";

        private UUID widgetId;

        private Builder() {
        }

        private Builder(DeletedEvent source) {
            this.type = source.type;
            this.widgetId = source.widgetId;
        }

        /**
         * Required.
         */
        public Builder widgetId(UUID widgetId) {
            this.widgetId = widgetId;
            return this;
        }

        /**
         * The {@link DeletedEvent}.
         *
         * @return the value
         * @throws ValidationException when it breaks the API's constraints (every problem is listed)
         */
        public DeletedEvent build() {
            DeletedEvent built = new DeletedEvent(type, widgetId);
            built.validate();
            return built;
        }
    }
}
