// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Kindgi Inc.
//
// Generated by kindgi-codegen-maven-plugin from the Kindgi API's openapi.json; do not edit.
package com.kindgi.client.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import org.jspecify.annotations.Nullable;

/**
 * @param id Required.
 * @param additionalProperties properties this client doesn't know, kept as they came
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public record Flow(@JsonProperty("id") String id,
        @JsonAnySetter @JsonAnyGetter Map<String, Object> additionalProperties) implements Model {
    public Flow {
        id = Checks.required(id, "Flow.id");
        additionalProperties = Checks.extras(additionalProperties);
    }

    @Override
    public void validate(Checks checks) {
    }

    /**
     * A builder for a {@link Flow}.
     *
     * @return the builder
     */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * A builder that starts from this value.
     *
     * @return the builder
     */
    public Builder toBuilder() {
        return new Builder(this);
    }

    /**
     * Builds a {@link Flow}; {@link #build()} checks it against the API's constraints.
     */
    public static final class Builder {
        private String id;

        private LinkedHashMap<String, Object> additionalProperties = new LinkedHashMap<>();

        private Builder() {
        }

        private Builder(Flow source) {
            this.id = source.id;
            this.additionalProperties.putAll(source.additionalProperties());
        }

        /**
         * Required.
         */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /**
         * Adds a property beside the known ones.
         */
        public Builder putAdditionalProperty(String key, @Nullable Object value) {
            this.additionalProperties.put(Objects.requireNonNull(key, "key"), value);
            return this;
        }

        /**
         * The {@link Flow}.
         *
         * @return the value
         * @throws ValidationException when it breaks the API's constraints (every problem is listed)
         */
        public Flow build() {
            Flow built = new Flow(id, additionalProperties);
            built.validate();
            return built;
        }
    }
}
