// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Kindgi Inc.
//
// Generated by kindgi-codegen-maven-plugin from the Kindgi API's openapi.json; do not edit.
package com.kindgi.client.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import org.jspecify.annotations.Nullable;

/**
 * @param id Required.
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public record Node(@JsonProperty("id") String id,
        @JsonProperty("children") @Nullable List<Node> children) implements Model {
    public Node {
        id = Checks.required(id, "Node.id");
        children = Checks.list(children);
    }

    @Override
    public void validate(Checks checks) {
        checks.nested("children", children);
    }

    /**
     * A builder for a {@link Node}.
     *
     * @return the builder
     */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * A builder that starts from this value.
     *
     * @return the builder
     */
    public Builder toBuilder() {
        return new Builder(this);
    }

    /**
     * Builds a {@link Node}; {@link #build()} checks it against the API's constraints.
     */
    public static final class Builder {
        private String id;

        private @Nullable List<Node> children;

        private Builder() {
        }

        private Builder(Node source) {
            this.id = source.id;
            this.children = source.children;
        }

        /**
         * Required.
         */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        public Builder children(@Nullable List<Node> children) {
            this.children = children;
            return this;
        }

        /**
         * The {@link Node}.
         *
         * @return the value
         * @throws ValidationException when it breaks the API's constraints (every problem is listed)
         */
        public Node build() {
            Node built = new Node(id, children);
            built.validate();
            return built;
        }
    }
}
