// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Kindgi Inc.
//
// Generated by kindgi-codegen-maven-plugin from the Kindgi API's openapi.json; do not edit.
package com.kindgi.client.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.regex.Pattern;

/**
 * @param id Required.
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public record Owner(@JsonProperty("id") String id) implements Model {
    private static final Pattern PATTERN_0 = Pattern.compile("^[a-z]");

    public Owner {
        id = Checks.required(id, "Owner.id");
    }

    @Override
    public void validate(Checks checks) {
        checks.pattern("id", id, PATTERN_0);
    }

    /**
     * A builder for a {@link Owner}.
     *
     * @return the builder
     */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * A builder that starts from this value.
     *
     * @return the builder
     */
    public Builder toBuilder() {
        return new Builder(this);
    }

    /**
     * Builds a {@link Owner}; {@link #build()} checks it against the API's constraints.
     */
    public static final class Builder {
        private String id;

        private Builder() {
        }

        private Builder(Owner source) {
            this.id = source.id;
        }

        /**
         * Required.
         */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /**
         * The {@link Owner}.
         *
         * @return the value
         * @throws ValidationException when it breaks the API's constraints (every problem is listed)
         */
        public Owner build() {
            Owner built = new Owner(id);
            built.validate();
            return built;
        }
    }
}
