// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Kindgi Inc.
//
// Generated by kindgi-codegen-maven-plugin from the Kindgi API's openapi.json; do not edit.
package com.kindgi.client.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

/**
 * @param note <code>null</code> clears it. Absent, an explicit {@code null}, or a value.
 * @param owner Absent, an explicit {@code null}, or a value.
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public record PatchWidgetBody(@JsonProperty("name") @Nullable String name,
        @JsonProperty("note") @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = OptionalNullable.AbsentFilter.class) OptionalNullable<String> note,
        @JsonProperty("owner") @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = OptionalNullable.AbsentFilter.class) OptionalNullable<Owner> owner) implements Model {
    public PatchWidgetBody {
        note = Checks.triState(note);
        owner = Checks.triState(owner);
    }

    @Override
    public void validate(Checks checks) {
        checks.minLength("name", name, 1);
        checks.nested("owner", owner.orElse(null));
    }

    /**
     * A builder for a {@link PatchWidgetBody}.
     *
     * @return the builder
     */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * A builder that starts from this value.
     *
     * @return the builder
     */
    public Builder toBuilder() {
        return new Builder(this);
    }

    /**
     * Builds a {@link PatchWidgetBody}; {@link #build()} checks it against the API's constraints.
     */
    public static final class Builder {
        private @Nullable String name;

        private OptionalNullable<String> note = OptionalNullable.absent();

        private OptionalNullable<Owner> owner = OptionalNullable.absent();

        private Builder() {
        }

        private Builder(PatchWidgetBody source) {
            this.name = source.name;
            this.note = source.note;
            this.owner = source.owner;
        }

        public Builder name(@Nullable String name) {
            this.name = name;
            return this;
        }

        /**
         * <code>null</code> clears it. Absent, an explicit {@code null}, or a value.
         * <p>A {@code null} sends an explicit {@code null}.
         */
        public Builder note(@Nullable String note) {
            this.note = OptionalNullable.of(note);
            return this;
        }

        /**
         * Absent, an explicit {@code null}, or a value.
         * <p>A {@code null} sends an explicit {@code null}.
         */
        public Builder owner(@Nullable Owner owner) {
            this.owner = OptionalNullable.of(owner);
            return this;
        }

        /**
         * The {@link PatchWidgetBody}.
         *
         * @return the value
         * @throws ValidationException when it breaks the API's constraints (every problem is listed)
         */
        public PatchWidgetBody build() {
            PatchWidgetBody built = new PatchWidgetBody(name, note, owner);
            built.validate();
            return built;
        }
    }
}
