// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Kindgi Inc.
//
// Generated by kindgi-codegen-maven-plugin from the Kindgi API's openapi.json; do not edit.
package com.kindgi.client.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * @param kind Always <code>prompt</code>.
 * @param blockId Required.
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public record PromptRef(@JsonProperty("kind") String kind,
        @JsonProperty("blockId") String blockId) implements WidgetInstructions {
    public PromptRef {
        kind = Checks.constant(kind, "prompt", "PromptRef.kind");
        blockId = Checks.required(blockId, "PromptRef.blockId");
    }

    @Override
    public void validate(Checks checks) {
    }

    /**
     * A builder for a {@link PromptRef}.
     *
     * @return the builder
     */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * A builder that starts from this value.
     *
     * @return the builder
     */
    public Builder toBuilder() {
        return new Builder(this);
    }

    /**
     * Builds a {@link PromptRef}; {@link #build()} checks it against the API's constraints.
     */
    public static final class Builder {
        private String kind = "prompt";

        private String blockId;

        private Builder() {
        }

        private Builder(PromptRef source) {
            this.kind = source.kind;
            this.blockId = source.blockId;
        }

        /**
         * Required.
         */
        public Builder blockId(String blockId) {
            this.blockId = blockId;
            return this;
        }

        /**
         * The {@link PromptRef}.
         *
         * @return the value
         * @throws ValidationException when it breaks the API's constraints (every problem is listed)
         */
        public PromptRef build() {
            PromptRef built = new PromptRef(kind, blockId);
            built.validate();
            return built;
        }
    }
}
