// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Kindgi Inc.
//
// Generated by kindgi-codegen-maven-plugin from the Kindgi API's openapi.json; do not edit.
package com.kindgi.client.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * @param jobId Required.
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public record RotateQueued(@JsonProperty("jobId") String jobId) implements WidgetsRotateResponse {
    public RotateQueued {
        jobId = Checks.required(jobId, "RotateQueued.jobId");
    }

    @Override
    public void validate(Checks checks) {
    }

    /**
     * A builder for a {@link RotateQueued}.
     *
     * @return the builder
     */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * A builder that starts from this value.
     *
     * @return the builder
     */
    public Builder toBuilder() {
        return new Builder(this);
    }

    /**
     * Builds a {@link RotateQueued}; {@link #build()} checks it against the API's constraints.
     */
    public static final class Builder {
        private String jobId;

        private Builder() {
        }

        private Builder(RotateQueued source) {
            this.jobId = source.jobId;
        }

        /**
         * Required.
         */
        public Builder jobId(String jobId) {
            this.jobId = jobId;
            return this;
        }

        /**
         * The {@link RotateQueued}.
         *
         * @return the value
         * @throws ValidationException when it breaks the API's constraints (every problem is listed)
         */
        public RotateQueued build() {
            RotateQueued built = new RotateQueued(jobId);
            built.validate();
            return built;
        }
    }
}
