// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Kindgi Inc.
//
// Generated by kindgi-codegen-maven-plugin from the Kindgi API's openapi.json; do not edit.
package com.kindgi.client.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.OffsetDateTime;

/**
 * @param rotatedAt Required.
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public record RotateDone(
        @JsonProperty("rotatedAt") OffsetDateTime rotatedAt) implements WidgetsRotateResponse {
    public RotateDone {
        rotatedAt = Checks.required(rotatedAt, "RotateDone.rotatedAt");
    }

    @Override
    public void validate(Checks checks) {
    }

    /**
     * A builder for a {@link RotateDone}.
     *
     * @return the builder
     */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * A builder that starts from this value.
     *
     * @return the builder
     */
    public Builder toBuilder() {
        return new Builder(this);
    }

    /**
     * Builds a {@link RotateDone}; {@link #build()} checks it against the API's constraints.
     */
    public static final class Builder {
        private OffsetDateTime rotatedAt;

        private Builder() {
        }

        private Builder(RotateDone source) {
            this.rotatedAt = source.rotatedAt;
        }

        /**
         * Required.
         */
        public Builder rotatedAt(OffsetDateTime rotatedAt) {
            this.rotatedAt = rotatedAt;
            return this;
        }

        /**
         * The {@link RotateDone}.
         *
         * @return the value
         * @throws ValidationException when it breaks the API's constraints (every problem is listed)
         */
        public RotateDone build() {
            RotateDone built = new RotateDone(rotatedAt);
            built.validate();
            return built;
        }
    }
}
