// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Kindgi Inc.
//
// Generated by kindgi-codegen-maven-plugin from the Kindgi API's openapi.json; do not edit.
package com.kindgi.client.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.regex.Pattern;

/**
 * @param key Required.
 * @param value Required.
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public record ScopeSegment(@JsonProperty("key") String key,
        @JsonProperty("value") String value) implements Model {
    private static final Pattern PATTERN_0 = Pattern.compile("^[a-z][a-z0-9_-]{0,63}$");

    public ScopeSegment {
        key = Checks.required(key, "ScopeSegment.key");
        value = Checks.required(value, "ScopeSegment.value");
    }

    @Override
    public void validate(Checks checks) {
        checks.pattern("key", key, PATTERN_0);
        checks.minLength("value", value, 1);
        checks.maxLength("value", value, 256);
    }

    /**
     * A builder for a {@link ScopeSegment}.
     *
     * @return the builder
     */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * A builder that starts from this value.
     *
     * @return the builder
     */
    public Builder toBuilder() {
        return new Builder(this);
    }

    /**
     * Builds a {@link ScopeSegment}; {@link #build()} checks it against the API's constraints.
     */
    public static final class Builder {
        private String key;

        private String value;

        private Builder() {
        }

        private Builder(ScopeSegment source) {
            this.key = source.key;
            this.value = source.value;
        }

        /**
         * Required.
         */
        public Builder key(String key) {
            this.key = key;
            return this;
        }

        /**
         * Required.
         */
        public Builder value(String value) {
            this.value = value;
            return this;
        }

        /**
         * The {@link ScopeSegment}.
         *
         * @return the value
         * @throws ValidationException when it breaks the API's constraints (every problem is listed)
         */
        public ScopeSegment build() {
            ScopeSegment built = new ScopeSegment(key, value);
            built.validate();
            return built;
        }
    }
}
