// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Kindgi Inc.
//
// Generated by kindgi-codegen-maven-plugin from the Kindgi API's openapi.json; do not edit.
package com.kindgi.client.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Map;
import java.util.Objects;

/**
 * One of the values below, or one this client doesn't know yet: {@link #of} keeps any value, and {@link #value()} is {@code UNRECOGNIZED} for an unknown one. Switch on {@link #value()}.
 */
public final class SettingsPutDomain {
    /**
     * <code>runs</code>
     */
    public static final SettingsPutDomain RUNS = new SettingsPutDomain("runs", Value.RUNS);

    /**
     * <code>memory</code>
     */
    public static final SettingsPutDomain MEMORY = new SettingsPutDomain("memory", Value.MEMORY);

    private static final Map<String, SettingsPutDomain> byValue = Map.ofEntries(
        Map.entry("runs", RUNS),
        Map.entry("memory", MEMORY));

    private final String raw;

    private final Value value;

    private SettingsPutDomain(String raw, Value value) {
        this.raw = raw;
        this.value = value;
    }

    /**
     * The value for this text: a known constant, or an unrecognized value that keeps it.
     */
    @JsonCreator
    public static SettingsPutDomain of(String raw) {
        SettingsPutDomain known = byValue.get(Objects.requireNonNull(raw, "raw"));
        return known != null ? known : new SettingsPutDomain(raw, Value.UNRECOGNIZED);
    }

    /**
     * The value as the API spells it.
     */
    @JsonValue
    public String asString() {
        return raw;
    }

    /**
     * Which known value this is, or {@code UNRECOGNIZED}.
     */
    public Value value() {
        return value;
    }

    /**
     * Whether this client knows the value.
     */
    public boolean isKnown() {
        return value != Value.UNRECOGNIZED;
    }

    @Override
    public boolean equals(Object other) {
        return other instanceof SettingsPutDomain && ((SettingsPutDomain) other).raw.equals(raw);
    }

    @Override
    public int hashCode() {
        return raw.hashCode();
    }

    @Override
    public String toString() {
        return raw;
    }

    /**
     * The values this client knows, and {@code UNRECOGNIZED}.
     */
    public enum Value {
        RUNS,

        MEMORY,

        UNRECOGNIZED
    }
}
