// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Kindgi Inc.
//
// Generated by kindgi-codegen-maven-plugin from the Kindgi API's openapi.json; do not edit.
package com.kindgi.client.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Map;
import java.util.Objects;

/**
 * @param mode Required.
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public record SettingsPutBody(@JsonProperty("mode") SettingsPutBody.Mode mode) implements Model {
    public SettingsPutBody {
        mode = Checks.required(mode, "SettingsPutBody.mode");
    }

    @Override
    public void validate(Checks checks) {
    }

    /**
     * A builder for a {@link SettingsPutBody}.
     *
     * @return the builder
     */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * A builder that starts from this value.
     *
     * @return the builder
     */
    public Builder toBuilder() {
        return new Builder(this);
    }

    /**
     * Builds a {@link SettingsPutBody}; {@link #build()} checks it against the API's constraints.
     */
    public static final class Builder {
        private Mode mode;

        private Builder() {
        }

        private Builder(SettingsPutBody source) {
            this.mode = source.mode;
        }

        /**
         * Required.
         */
        public Builder mode(Mode mode) {
            this.mode = mode;
            return this;
        }

        /**
         * The {@link SettingsPutBody}.
         *
         * @return the value
         * @throws ValidationException when it breaks the API's constraints (every problem is listed)
         */
        public SettingsPutBody build() {
            SettingsPutBody built = new SettingsPutBody(mode);
            built.validate();
            return built;
        }
    }

    /**
     * One of the values below, or one this client doesn't know yet: {@link #of} keeps any value, and {@link #value()} is {@code UNRECOGNIZED} for an unknown one. Switch on {@link #value()}.
     */
    public static final class Mode {
        /**
         * <code>strict</code>
         */
        public static final Mode STRICT = new Mode("strict", Value.STRICT);

        /**
         * <code>lenient</code>
         */
        public static final Mode LENIENT = new Mode("lenient", Value.LENIENT);

        private static final Map<String, Mode> byValue = Map.ofEntries(
            Map.entry("strict", STRICT),
            Map.entry("lenient", LENIENT));

        private final String raw;

        private final Value value;

        private Mode(String raw, Value value) {
            this.raw = raw;
            this.value = value;
        }

        /**
         * The value for this text: a known constant, or an unrecognized value that keeps it.
         */
        @JsonCreator
        public static Mode of(String raw) {
            Mode known = byValue.get(Objects.requireNonNull(raw, "raw"));
            return known != null ? known : new Mode(raw, Value.UNRECOGNIZED);
        }

        /**
         * The value as the API spells it.
         */
        @JsonValue
        public String asString() {
            return raw;
        }

        /**
         * Which known value this is, or {@code UNRECOGNIZED}.
         */
        public Value value() {
            return value;
        }

        /**
         * Whether this client knows the value.
         */
        public boolean isKnown() {
            return value != Value.UNRECOGNIZED;
        }

        @Override
        public boolean equals(Object other) {
            return other instanceof Mode && ((Mode) other).raw.equals(raw);
        }

        @Override
        public int hashCode() {
            return raw.hashCode();
        }

        @Override
        public String toString() {
            return raw;
        }

        /**
         * The values this client knows, and {@code UNRECOGNIZED}.
         */
        public enum Value {
            STRICT,

            LENIENT,

            UNRECOGNIZED
        }
    }
}
