// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Kindgi Inc.
//
// Generated by kindgi-codegen-maven-plugin from the Kindgi API's openapi.json; do not edit.
package com.kindgi.client.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * @param applied Required.
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public record SettingsPutResponse(@JsonProperty("applied") Boolean applied) implements Model {
    public SettingsPutResponse {
        applied = Checks.required(applied, "SettingsPutResponse.applied");
    }

    @Override
    public void validate(Checks checks) {
    }

    /**
     * A builder for a {@link SettingsPutResponse}.
     *
     * @return the builder
     */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * A builder that starts from this value.
     *
     * @return the builder
     */
    public Builder toBuilder() {
        return new Builder(this);
    }

    /**
     * Builds a {@link SettingsPutResponse}; {@link #build()} checks it against the API's constraints.
     */
    public static final class Builder {
        private Boolean applied;

        private Builder() {
        }

        private Builder(SettingsPutResponse source) {
            this.applied = source.applied;
        }

        /**
         * Required.
         */
        public Builder applied(Boolean applied) {
            this.applied = applied;
            return this;
        }

        /**
         * The {@link SettingsPutResponse}.
         *
         * @return the value
         * @throws ValidationException when it breaks the API's constraints (every problem is listed)
         */
        public SettingsPutResponse build() {
            SettingsPutResponse built = new SettingsPutResponse(applied);
            built.validate();
            return built;
        }
    }
}
