// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Kindgi Inc.
//
// Generated by kindgi-codegen-maven-plugin from the Kindgi API's openapi.json; do not edit.
package com.kindgi.client.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import java.util.List;
import java.util.Map;
import org.jspecify.annotations.Nullable;

/**
 * One of:
 * <ul>
 * <li>{@link Circle}: {@code kind} is <code>circle</code></li>
 * <li>{@link Square}: {@code kind} is <code>square</code></li>
 * <li>{@link Shape.DotOrPoint}: {@code kind} is <code>dot</code> or <code>point</code></li>
 * <li>{@link Unrecognized}: a variant this client doesn't know yet, kept as it came</li>
 * </ul>
 */
@JsonTypeInfo(
        use = JsonTypeInfo.Id.NAME,
        include = JsonTypeInfo.As.EXISTING_PROPERTY,
        property = "kind",
        visible = true,
        defaultImpl = Shape.Unrecognized.class
)
@JsonSubTypes({
        @JsonSubTypes.Type(value = Circle.class, name = "circle"),
        @JsonSubTypes.Type(value = Square.class, name = "square"),
        @JsonSubTypes.Type(value = Shape.DotOrPoint.class, names = {"dot", "point"})
})
public sealed interface Shape extends Model permits Circle, Square, Shape.DotOrPoint, Shape.Unrecognized {
    /**
     * The {@code kind} that tells the variants apart.
     */
    String kind();

    /**
     * A variant this client doesn't know yet (a newer runtime's), kept as it came.
     *
     * @param kind its {@code kind}
     * @param properties its other properties
     */
    @JsonInclude(JsonInclude.Include.NON_NULL)
    record Unrecognized(@JsonProperty("kind") @Nullable String kind,
            @JsonAnySetter @JsonAnyGetter Map<String, Object> properties) implements Shape {
        public Unrecognized {
            properties = Checks.extras(properties);
        }

        @Override
        public void validate(Checks checks) {
            // Nothing to check: the client doesn't know this variant's constraints.
        }
    }

    /**
     * @param x Required.
     */
    @JsonInclude(JsonInclude.Include.NON_NULL)
    record DotOrPoint(@JsonProperty("kind") String kind,
            @JsonProperty("x") Double x) implements Shape {
        public DotOrPoint {
            kind = Checks.required(kind, "Shape.DotOrPoint.kind");
            x = Checks.required(x, "Shape.DotOrPoint.x");
        }

        @Override
        public void validate(Checks checks) {
            checks.oneOf("kind", kind, List.of("dot", "point"));
        }

        /**
         * A builder for a {@link DotOrPoint}.
         *
         * @return the builder
         */
        public static Builder builder() {
            return new Builder();
        }

        /**
         * A builder that starts from this value.
         *
         * @return the builder
         */
        public Builder toBuilder() {
            return new Builder(this);
        }

        /**
         * Builds a {@link DotOrPoint}; {@link #build()} checks it against the API's constraints.
         */
        public static final class Builder {
            private String kind;

            private Double x;

            private Builder() {
            }

            private Builder(DotOrPoint source) {
                this.kind = source.kind;
                this.x = source.x;
            }

            public Builder kind(String kind) {
                this.kind = kind;
                return this;
            }

            /**
             * Required.
             */
            public Builder x(Double x) {
                this.x = x;
                return this;
            }

            /**
             * The {@link DotOrPoint}.
             *
             * @return the value
             * @throws ValidationException when it breaks the API's constraints (every problem is listed)
             */
            public DotOrPoint build() {
                DotOrPoint built = new DotOrPoint(kind, x);
                built.validate();
                return built;
            }
        }
    }
}
