// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Kindgi Inc.
//
// Generated by kindgi-codegen-maven-plugin from the Kindgi API's openapi.json; do not edit.
package com.kindgi.client.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * @param side Required.
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public record Square(@JsonProperty("kind") String kind,
        @JsonProperty("side") Double side) implements Shape {
    public Square {
        kind = Checks.constant(kind, "square", "Square.kind");
        side = Checks.required(side, "Square.side");
    }

    @Override
    public void validate(Checks checks) {
    }

    /**
     * A builder for a {@link Square}.
     *
     * @return the builder
     */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * A builder that starts from this value.
     *
     * @return the builder
     */
    public Builder toBuilder() {
        return new Builder(this);
    }

    /**
     * Builds a {@link Square}; {@link #build()} checks it against the API's constraints.
     */
    public static final class Builder {
        private String kind = "square";

        private Double side;

        private Builder() {
        }

        private Builder(Square source) {
            this.kind = source.kind;
            this.side = source.side;
        }

        /**
         * Required.
         */
        public Builder side(Double side) {
            this.side = side;
            return this;
        }

        /**
         * The {@link Square}.
         *
         * @return the value
         * @throws ValidationException when it breaks the API's constraints (every problem is listed)
         */
        public Square build() {
            Square built = new Square(kind, side);
            built.validate();
            return built;
        }
    }
}
