// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Kindgi Inc.
//
// Generated by kindgi-codegen-maven-plugin from the Kindgi API's openapi.json; do not edit.
package com.kindgi.client.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.UUID;
import org.jspecify.annotations.Nullable;

/**
 * @param file Required.
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public record UploadBody(@JsonProperty("file") byte[] file,
        @JsonProperty("name") @Nullable String name,
        @JsonProperty("ownerId") @Nullable UUID ownerId) implements Model {
    public UploadBody {
        file = Checks.required(file, "UploadBody.file");
    }

    @Override
    public void validate(Checks checks) {
    }

    /**
     * A builder for a {@link UploadBody}.
     *
     * @return the builder
     */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * A builder that starts from this value.
     *
     * @return the builder
     */
    public Builder toBuilder() {
        return new Builder(this);
    }

    /**
     * Builds a {@link UploadBody}; {@link #build()} checks it against the API's constraints.
     */
    public static final class Builder {
        private byte[] file;

        private @Nullable String name;

        private @Nullable UUID ownerId;

        private Builder() {
        }

        private Builder(UploadBody source) {
            this.file = source.file;
            this.name = source.name;
            this.ownerId = source.ownerId;
        }

        /**
         * Required.
         */
        public Builder file(byte[] file) {
            this.file = file;
            return this;
        }

        public Builder name(@Nullable String name) {
            this.name = name;
            return this;
        }

        public Builder ownerId(@Nullable UUID ownerId) {
            this.ownerId = ownerId;
            return this;
        }

        /**
         * The {@link UploadBody}.
         *
         * @return the value
         * @throws ValidationException when it breaks the API's constraints (every problem is listed)
         */
        public UploadBody build() {
            UploadBody built = new UploadBody(file, name, ownerId);
            built.validate();
            return built;
        }
    }
}
