// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Kindgi Inc.
//
// Generated by kindgi-codegen-maven-plugin from the Kindgi API's openapi.json; do not edit.
package com.kindgi.client.models;

import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Objects;

/**
 * One of:
 * <ul>
 * <li>{@link PromptRef}</li>
 * <li>{@link WidgetInstructions.Text}: text</li>
 * </ul>
 */
public sealed interface WidgetInstructions extends Model permits PromptRef, WidgetInstructions.Text {
    /**
     * The text variant.
     */
    static WidgetInstructions of(String text) {
        return new Text(text);
    }

    /**
     * The text variant.
     *
     * @param value the text
     */
    record Text(@JsonValue String value) implements WidgetInstructions {
        public Text {
            Objects.requireNonNull(value, "WidgetInstructions text");
        }

        @Override
        public void validate(Checks checks) {
        }
    }
}
