// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Kindgi Inc.
//
// Generated by kindgi-codegen-maven-plugin from the Kindgi API's openapi.json; do not edit.
package com.kindgi.client.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.OffsetDateTime;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import java.util.regex.Pattern;
import org.jspecify.annotations.Nullable;

/**
 * A widget.
 *
 * @param id Required.
 * @param name Its <code>name</code>. Required.
 * @param state Required.
 * @param label Required, but may be null.
 * @param note Absent, an explicit {@code null}, or a value.
 * @param kind Always <code>widget</code>.
 * @param shape Required.
 * @param extra Any JSON.
 * @param wait_ Defaults to <code>false</code> on the server.
 * @param owner Absent, an explicit {@code null}, or a value.
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public record Widget(@JsonProperty("id") UUID id, @JsonProperty("name") String name,
        @JsonProperty("state") WidgetState state, @JsonProperty("label") @Nullable String label,
        @JsonProperty("note") @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = OptionalNullable.AbsentFilter.class) OptionalNullable<String> note,
        @JsonProperty("createdAt") @Nullable OffsetDateTime createdAt,
        @JsonProperty("tags") @Nullable List<String> tags,
        @JsonProperty("labels") @Nullable Map<String, String> labels,
        @JsonProperty("size") Widget. @Nullable Size size, @JsonProperty("kind") String kind,
        @JsonProperty("shape") Shape shape, @JsonProperty("content") @Nullable Content content,
        @JsonProperty("instructions") @Nullable WidgetInstructions instructions,
        @JsonProperty("baseline") @Nullable Baseline baseline,
        @JsonProperty("score") @Nullable Object score,
        @JsonProperty("stamp") @Nullable String stamp,
        @JsonProperty("restricted") @Nullable Boolean restricted,
        @JsonProperty("extra") @Nullable Object extra,
        @JsonProperty("wait") @Nullable Boolean wait_,
        @JsonProperty("default") @Nullable String default_,
        @JsonProperty("owner") @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = OptionalNullable.AbsentFilter.class) OptionalNullable<Owner> owner,
        @JsonProperty("flow") @Nullable Flow flow,
        @JsonProperty("nodes") @Nullable List<Node> nodes) implements Model {
    private static final Pattern PATTERN_0 = Pattern.compile("^[a-z]+$");

    public Widget {
        id = Checks.required(id, "Widget.id");
        name = Checks.required(name, "Widget.name");
        state = Checks.required(state, "Widget.state");
        note = Checks.triState(note);
        tags = Checks.list(tags);
        labels = Checks.map(labels);
        kind = Checks.constant(kind, "widget", "Widget.kind");
        shape = Checks.required(shape, "Widget.shape");
        owner = Checks.triState(owner);
        nodes = Checks.list(nodes);
    }

    @Override
    public void validate(Checks checks) {
        checks.minLength("name", name, 1);
        checks.maxLength("name", name, 64);
        checks.maxLength("note", note.orElse(null), 500);
        checks.maxItems("tags", tags, 8);
        checks.uniqueItems("tags", tags);
        checks.eachItem("tags", tags, item0 -> {
            checks.minLength("", item0, 1);
        });
        checks.maxProperties("labels", labels, 4);
        checks.eachKey("labels", labels, key0 -> {
            checks.pattern("", key0, PATTERN_0);
        });
        checks.eachValue("labels", labels, entry0 -> {
            checks.maxLength("", entry0, 32);
        });
        checks.nested("size", size);
        checks.nested("shape", shape);
        checks.nested("content", content);
        checks.nested("instructions", instructions);
        checks.nested("baseline", baseline);
        checks.nested("owner", owner.orElse(null));
        checks.nested("flow", flow);
        checks.nested("nodes", nodes);
    }

    /**
     * A builder for a {@link Widget}.
     *
     * @return the builder
     */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * A builder that starts from this value.
     *
     * @return the builder
     */
    public Builder toBuilder() {
        return new Builder(this);
    }

    /**
     * Builds a {@link Widget}; {@link #build()} checks it against the API's constraints.
     */
    public static final class Builder {
        private UUID id;

        private String name;

        private WidgetState state;

        private @Nullable String label;

        private OptionalNullable<String> note = OptionalNullable.absent();

        private @Nullable OffsetDateTime createdAt;

        private @Nullable List<String> tags;

        private @Nullable Map<String, String> labels;

        private @Nullable Size size;

        private String kind = "widget";

        private Shape shape;

        private @Nullable Content content;

        private @Nullable WidgetInstructions instructions;

        private @Nullable Baseline baseline;

        private @Nullable Object score;

        private @Nullable String stamp;

        private @Nullable Boolean restricted;

        private @Nullable Object extra;

        private @Nullable Boolean wait_;

        private @Nullable String default_;

        private OptionalNullable<Owner> owner = OptionalNullable.absent();

        private @Nullable Flow flow;

        private @Nullable List<Node> nodes;

        private Builder() {
        }

        private Builder(Widget source) {
            this.id = source.id;
            this.name = source.name;
            this.state = source.state;
            this.label = source.label;
            this.note = source.note;
            this.createdAt = source.createdAt;
            this.tags = source.tags;
            this.labels = source.labels;
            this.size = source.size;
            this.kind = source.kind;
            this.shape = source.shape;
            this.content = source.content;
            this.instructions = source.instructions;
            this.baseline = source.baseline;
            this.score = source.score;
            this.stamp = source.stamp;
            this.restricted = source.restricted;
            this.extra = source.extra;
            this.wait_ = source.wait_;
            this.default_ = source.default_;
            this.owner = source.owner;
            this.flow = source.flow;
            this.nodes = source.nodes;
        }

        /**
         * Required.
         */
        public Builder id(UUID id) {
            this.id = id;
            return this;
        }

        /**
         * Its <code>name</code>. Required.
         */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        /**
         * Required.
         */
        public Builder state(WidgetState state) {
            this.state = state;
            return this;
        }

        /**
         * Required, but may be null.
         */
        public Builder label(@Nullable String label) {
            this.label = label;
            return this;
        }

        /**
         * Absent, an explicit {@code null}, or a value.
         * <p>A {@code null} sends an explicit {@code null}.
         */
        public Builder note(@Nullable String note) {
            this.note = OptionalNullable.of(note);
            return this;
        }

        public Builder createdAt(@Nullable OffsetDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        public Builder tags(@Nullable List<String> tags) {
            this.tags = tags;
            return this;
        }

        public Builder labels(@Nullable Map<String, String> labels) {
            this.labels = labels;
            return this;
        }

        public Builder size(@Nullable Size size) {
            this.size = size;
            return this;
        }

        /**
         * Required.
         */
        public Builder shape(Shape shape) {
            this.shape = shape;
            return this;
        }

        public Builder content(@Nullable Content content) {
            this.content = content;
            return this;
        }

        public Builder instructions(@Nullable WidgetInstructions instructions) {
            this.instructions = instructions;
            return this;
        }

        /**
         * The text form of {@link #instructions(WidgetInstructions)}.
         */
        public Builder instructions(String instructions) {
            this.instructions = new WidgetInstructions.Text(instructions);
            return this;
        }

        public Builder baseline(@Nullable Baseline baseline) {
            this.baseline = baseline;
            return this;
        }

        /**
         * The text form of {@link #baseline(Baseline)}.
         */
        public Builder baseline(String baseline) {
            this.baseline = new Baseline.Recorded(baseline);
            return this;
        }

        public Builder score(@Nullable Object score) {
            this.score = score;
            return this;
        }

        public Builder stamp(@Nullable String stamp) {
            this.stamp = stamp;
            return this;
        }

        public Builder restricted(@Nullable Boolean restricted) {
            this.restricted = restricted;
            return this;
        }

        /**
         * Any JSON.
         */
        public Builder extra(@Nullable Object extra) {
            this.extra = extra;
            return this;
        }

        /**
         * Defaults to <code>false</code> on the server.
         */
        public Builder wait_(@Nullable Boolean wait_) {
            this.wait_ = wait_;
            return this;
        }

        public Builder default_(@Nullable String default_) {
            this.default_ = default_;
            return this;
        }

        /**
         * Absent, an explicit {@code null}, or a value.
         * <p>A {@code null} sends an explicit {@code null}.
         */
        public Builder owner(@Nullable Owner owner) {
            this.owner = OptionalNullable.of(owner);
            return this;
        }

        public Builder flow(@Nullable Flow flow) {
            this.flow = flow;
            return this;
        }

        public Builder nodes(@Nullable List<Node> nodes) {
            this.nodes = nodes;
            return this;
        }

        /**
         * The {@link Widget}.
         *
         * @return the value
         * @throws ValidationException when it breaks the API's constraints (every problem is listed)
         */
        public Widget build() {
            Widget built = new Widget(id, name, state, label, note, createdAt, tags, labels, size, kind, shape, content, instructions, baseline, score, stamp, restricted, extra, wait_, default_, owner, flow, nodes);
            built.validate();
            return built;
        }
    }

    @JsonInclude(JsonInclude.Include.NON_NULL)
    public static record Size(@JsonProperty("width") @Nullable Long width,
            @JsonProperty("height") @Nullable Double height) implements Model {
        @Override
        public void validate(Checks checks) {
            checks.minimum("width", width, "0");
            checks.exclusiveMinimum("height", height, "0");
        }

        /**
         * A builder for a {@link Size}.
         *
         * @return the builder
         */
        public static Builder builder() {
            return new Builder();
        }

        /**
         * A builder that starts from this value.
         *
         * @return the builder
         */
        public Builder toBuilder() {
            return new Builder(this);
        }

        /**
         * Builds a {@link Size}; {@link #build()} checks it against the API's constraints.
         */
        public static final class Builder {
            private @Nullable Long width;

            private @Nullable Double height;

            private Builder() {
            }

            private Builder(Size source) {
                this.width = source.width;
                this.height = source.height;
            }

            public Builder width(@Nullable Long width) {
                this.width = width;
                return this;
            }

            public Builder height(@Nullable Double height) {
                this.height = height;
                return this;
            }

            /**
             * The {@link Size}.
             *
             * @return the value
             * @throws ValidationException when it breaks the API's constraints (every problem is listed)
             */
            public Size build() {
                Size built = new Size(width, height);
                built.validate();
                return built;
            }
        }
    }
}
