// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Kindgi Inc.
//
// Generated by kindgi-codegen-maven-plugin from the Kindgi API's openapi.json; do not edit.
package com.kindgi.client.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

/**
 * @param name Required.
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public record WidgetCore(@JsonProperty("name") String name,
        @JsonProperty("state") @Nullable WidgetState state) implements Model {
    public WidgetCore {
        name = Checks.required(name, "WidgetCore.name");
    }

    @Override
    public void validate(Checks checks) {
        checks.minLength("name", name, 1);
    }

    /**
     * A builder for a {@link WidgetCore}.
     *
     * @return the builder
     */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * A builder that starts from this value.
     *
     * @return the builder
     */
    public Builder toBuilder() {
        return new Builder(this);
    }

    /**
     * Builds a {@link WidgetCore}; {@link #build()} checks it against the API's constraints.
     */
    public static final class Builder {
        private String name;

        private @Nullable WidgetState state;

        private Builder() {
        }

        private Builder(WidgetCore source) {
            this.name = source.name;
            this.state = source.state;
        }

        /**
         * Required.
         */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        public Builder state(@Nullable WidgetState state) {
            this.state = state;
            return this;
        }

        /**
         * The {@link WidgetCore}.
         *
         * @return the value
         * @throws ValidationException when it breaks the API's constraints (every problem is listed)
         */
        public WidgetCore build() {
            WidgetCore built = new WidgetCore(name, state);
            built.validate();
            return built;
        }
    }
}
