// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Kindgi Inc.
//
// Generated by kindgi-codegen-maven-plugin from the Kindgi API's openapi.json; do not edit.
package com.kindgi.client.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import java.util.Map;
import org.jspecify.annotations.Nullable;

/**
 * One of:
 * <ul>
 * <li>{@link CreatedEvent}: {@code type} is <code>widget.created</code></li>
 * <li>{@link DeletedEvent}: {@code type} is <code>widget.deleted</code></li>
 * <li>{@link Unrecognized}: a variant this client doesn't know yet, kept as it came</li>
 * </ul>
 */
@JsonTypeInfo(
        use = JsonTypeInfo.Id.NAME,
        include = JsonTypeInfo.As.EXISTING_PROPERTY,
        property = "type",
        visible = true,
        defaultImpl = WidgetEvent.Unrecognized.class
)
@JsonSubTypes({
        @JsonSubTypes.Type(value = CreatedEvent.class, name = "widget.created"),
        @JsonSubTypes.Type(value = DeletedEvent.class, name = "widget.deleted")
})
public sealed interface WidgetEvent extends Model permits CreatedEvent, DeletedEvent, WidgetEvent.Unrecognized {
    /**
     * The {@code type} that tells the variants apart.
     */
    String type();

    /**
     * A variant this client doesn't know yet (a newer runtime's), kept as it came.
     *
     * @param type its {@code type}
     * @param properties its other properties
     */
    @JsonInclude(JsonInclude.Include.NON_NULL)
    record Unrecognized(@JsonProperty("type") @Nullable String type,
            @JsonAnySetter @JsonAnyGetter Map<String, Object> properties) implements WidgetEvent {
        public Unrecognized {
            properties = Checks.extras(properties);
        }

        @Override
        public void validate(Checks checks) {
            // Nothing to check: the client doesn't know this variant's constraints.
        }
    }
}
