// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Kindgi Inc.
//
// Generated by kindgi-codegen-maven-plugin from the Kindgi API's openapi.json; do not edit.
package com.kindgi.client.models;

/**
 * The answer of &#123;&#64;code widgets.rotate&#125;, by HTTP status.
 *
 * <p>One of:
 * <ul>
 * <li>{@link RotateDone}</li>
 * <li>{@link RotateQueued}</li>
 * </ul>
 */
public sealed interface WidgetsRotateResponse extends Model permits RotateDone, RotateQueued {
}
