// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Kindgi Inc.
//
// Generated by kindgi-codegen-maven-plugin from the Kindgi API's openapi.json; do not edit.
package com.kindgi.client.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import org.jspecify.annotations.Nullable;

/**
 * @param data Required.
 * @param hasMore Required.
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public record WidgetPage(@JsonProperty("data") List<Widget> data,
        @JsonProperty("hasMore") Boolean hasMore,
        @JsonProperty("nextCursor") @Nullable String nextCursor) implements Model {
    public WidgetPage {
        data = Checks.required(data, "WidgetPage.data");
        data = Checks.list(data);
        hasMore = Checks.required(hasMore, "WidgetPage.hasMore");
    }

    @Override
    public void validate(Checks checks) {
        checks.nested("data", data);
    }

    /**
     * A builder for a {@link WidgetPage}.
     *
     * @return the builder
     */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * A builder that starts from this value.
     *
     * @return the builder
     */
    public Builder toBuilder() {
        return new Builder(this);
    }

    /**
     * Builds a {@link WidgetPage}; {@link #build()} checks it against the API's constraints.
     */
    public static final class Builder {
        private List<Widget> data;

        private Boolean hasMore;

        private @Nullable String nextCursor;

        private Builder() {
        }

        private Builder(WidgetPage source) {
            this.data = source.data;
            this.hasMore = source.hasMore;
            this.nextCursor = source.nextCursor;
        }

        /**
         * Required.
         */
        public Builder data(List<Widget> data) {
            this.data = data;
            return this;
        }

        /**
         * Required.
         */
        public Builder hasMore(Boolean hasMore) {
            this.hasMore = hasMore;
            return this;
        }

        public Builder nextCursor(@Nullable String nextCursor) {
            this.nextCursor = nextCursor;
            return this;
        }

        /**
         * The {@link WidgetPage}.
         *
         * @return the value
         * @throws ValidationException when it breaks the API's constraints (every problem is listed)
         */
        public WidgetPage build() {
            WidgetPage built = new WidgetPage(data, hasMore, nextCursor);
            built.validate();
            return built;
        }
    }
}
