// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Kindgi Inc.
//
// Generated by kindgi-codegen-maven-plugin from the Kindgi API's openapi.json; do not edit.
package com.kindgi.client.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Map;
import java.util.Objects;

/**
 * Where a widget is.
 *
 * <p>One of the values below, or one this client doesn't know yet: {@link #of} keeps any value, and {@link #value()} is {@code UNRECOGNIZED} for an unknown one. Switch on {@link #value()}.
 */
public final class WidgetState {
    /**
     * <code>draft</code>
     */
    public static final WidgetState DRAFT = new WidgetState("draft", Value.DRAFT);

    /**
     * <code>live</code>
     */
    public static final WidgetState LIVE = new WidgetState("live", Value.LIVE);

    /**
     * <code>archived</code>
     */
    public static final WidgetState ARCHIVED = new WidgetState("archived", Value.ARCHIVED);

    /**
     * <code>run.finished</code>
     */
    public static final WidgetState RUN_FINISHED = new WidgetState("run.finished", Value.RUN_FINISHED);

    private static final Map<String, WidgetState> byValue = Map.ofEntries(
        Map.entry("draft", DRAFT),
        Map.entry("live", LIVE),
        Map.entry("archived", ARCHIVED),
        Map.entry("run.finished", RUN_FINISHED));

    private final String raw;

    private final Value value;

    private WidgetState(String raw, Value value) {
        this.raw = raw;
        this.value = value;
    }

    /**
     * The value for this text: a known constant, or an unrecognized value that keeps it.
     */
    @JsonCreator
    public static WidgetState of(String raw) {
        WidgetState known = byValue.get(Objects.requireNonNull(raw, "raw"));
        return known != null ? known : new WidgetState(raw, Value.UNRECOGNIZED);
    }

    /**
     * The value as the API spells it.
     */
    @JsonValue
    public String asString() {
        return raw;
    }

    /**
     * Which known value this is, or {@code UNRECOGNIZED}.
     */
    public Value value() {
        return value;
    }

    /**
     * Whether this client knows the value.
     */
    public boolean isKnown() {
        return value != Value.UNRECOGNIZED;
    }

    @Override
    public boolean equals(Object other) {
        return other instanceof WidgetState && ((WidgetState) other).raw.equals(raw);
    }

    @Override
    public int hashCode() {
        return raw.hashCode();
    }

    @Override
    public String toString() {
        return raw;
    }

    /**
     * The values this client knows, and {@code UNRECOGNIZED}.
     */
    public enum Value {
        DRAFT,

        LIVE,

        ARCHIVED,

        RUN_FINISHED,

        UNRECOGNIZED
    }
}
