// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Kindgi Inc.

package com.kindgi.codegen;

import com.palantir.javapoet.AnnotationSpec;
import com.palantir.javapoet.ArrayTypeName;
import com.palantir.javapoet.ClassName;
import com.palantir.javapoet.CodeBlock;
import com.palantir.javapoet.FieldSpec;
import com.palantir.javapoet.JavaFile;
import com.palantir.javapoet.MethodSpec;
import com.palantir.javapoet.ParameterSpec;
import com.palantir.javapoet.ParameterizedTypeName;
import com.palantir.javapoet.TypeName;
import com.palantir.javapoet.TypeSpec;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.regex.Pattern;
import javax.lang.model.element.Modifier;

/** Writes the planned model types as Java source. */
final class ModelWriter {
  static final String MODELS = ModelPlanner.MODELS;
  private static final String ANN = "com.fasterxml.jackson.annotation";
  static final ClassName JSON_PROPERTY = ClassName.get(ANN, "JsonProperty");
  static final ClassName JSON_INCLUDE = ClassName.get(ANN, "JsonInclude");
  static final ClassName JSON_TYPE_INFO = ClassName.get(ANN, "JsonTypeInfo");
  static final ClassName JSON_SUB_TYPES = ClassName.get(ANN, "JsonSubTypes");
  static final ClassName JSON_ANY_SETTER = ClassName.get(ANN, "JsonAnySetter");
  static final ClassName JSON_ANY_GETTER = ClassName.get(ANN, "JsonAnyGetter");
  static final ClassName JSON_CREATOR = ClassName.get(ANN, "JsonCreator");
  static final ClassName JSON_VALUE = ClassName.get(ANN, "JsonValue");
  static final ClassName JSON_DESERIALIZE = ClassName.get("tools.jackson.databind.annotation", "JsonDeserialize");
  static final ClassName VALUE_DESERIALIZER = ClassName.get("tools.jackson.databind", "ValueDeserializer");
  static final ClassName DESER_CONTEXT = ClassName.get("tools.jackson.databind", "DeserializationContext");
  static final ClassName JSON_NODE = ClassName.get("tools.jackson.databind", "JsonNode");
  static final ClassName JSON_PARSER = ClassName.get("tools.jackson.core", "JsonParser");
  static final ClassName JSON_TOKEN = ClassName.get("tools.jackson.core", "JsonToken");
  static final ClassName NULLABLE = ClassName.get("org.jspecify.annotations", "Nullable");
  static final ClassName MODEL = ClassName.get(MODELS, "Model");
  static final ClassName CHECKS = ClassName.get(MODELS, "Checks");
  static final ClassName OPTIONAL_NULLABLE = ClassName.get(MODELS, "OptionalNullable");
  static final String HEADER =
      "SPDX-License-Identifier: Apache-2.0\nCopyright (C) 2026 Kindgi Inc.\n\n"
          + "Generated by kindgi-codegen-maven-plugin from the Kindgi API's openapi.json; do not edit.";

  private final ModelPlanner planner;

  ModelWriter(ModelPlanner planner) {
    this.planner = planner;
  }

  List<JavaFile> files() {
    List<JavaFile> out = new ArrayList<>();
    for (Ir.Decl d : planner.decls.values()) {
      out.add(file(d.name().packageName(), type(d)));
    }
    return out;
  }

  static JavaFile file(String pkg, TypeSpec type) {
    return JavaFile.builder(pkg, type)
        .addFileComment("$L", HEADER)
        .skipJavaLangImports(true)
        .indent("    ")
        .build();
  }

  private TypeSpec type(Ir.Decl d) {
    if (d instanceof Ir.RecordDecl) {
      return record((Ir.RecordDecl) d);
    }
    if (d instanceof Ir.EnumDecl) {
      return enumClass((Ir.EnumDecl) d);
    }
    return union((Ir.UnionDecl) d);
  }

  // ---------------------------------------------------------------------------------------------
  // Records
  // ---------------------------------------------------------------------------------------------

  private TypeSpec record(Ir.RecordDecl d) {
    ClassName cn = d.name;
    TypeSpec.Builder rb = TypeSpec.recordBuilder(cn).addModifiers(modifiers(cn));
    List<String> params = new ArrayList<>();
    rb.addAnnotation(
        AnnotationSpec.builder(JSON_INCLUDE).addMember("value", "$T.Include.NON_NULL", JSON_INCLUDE).build());
    if (d.interfaces.isEmpty()) {
      rb.addSuperinterface(MODEL);
    }
    for (ClassName i : d.interfaces) {
      rb.addSuperinterface(i);
    }
    String owner = String.join(".", cn.simpleNames());
    MethodSpec.Builder ctor = MethodSpec.compactConstructorBuilder().addModifiers(Modifier.PUBLIC);
    CodeBlock.Builder checks = CodeBlock.builder();
    PatternNames patterns = new PatternNames();
    for (Ir.Field f : d.fields) {
      ParameterSpec.Builder p = ParameterSpec.builder(componentType(f), f.java);
      p.addAnnotation(AnnotationSpec.builder(JSON_PROPERTY).addMember("value", "$S", f.wire).build());
      if (f.triState) {
        p.addAnnotation(
            AnnotationSpec.builder(JSON_INCLUDE)
                .addMember("value", "$T.Include.CUSTOM", JSON_INCLUDE)
                .addMember("valueFilter", "$T.AbsentFilter.class", OPTIONAL_NULLABLE)
                .build());
      }
      ctor.addParameter(p.build());
      String path = owner + "." + f.wire;
      if (f.tagValues != null && f.tagValues.size() == 1) {
        ctor.addStatement("$N = $T.constant($N, $S, $S)", f.java, CHECKS, f.java, f.tagValues.get(0), path);
      } else if (f.constValue != null) {
        ctor.addStatement("$N = $T.constant($N, $L, $S)", f.java, CHECKS, f.java, literal(f.constValue), path);
      } else if (f.triState) {
        ctor.addStatement("$N = $T.triState($N)", f.java, CHECKS, f.java);
      } else if (f.required && !f.nullable) {
        ctor.addStatement("$N = $T.required($N, $S)", f.java, CHECKS, f.java, path);
      }
      if (!f.triState) {
        TypeName raw = f.type;
        if (raw instanceof ParameterizedTypeName && ((ParameterizedTypeName) raw).rawType().equals(ModelPlanner.LIST)) {
          ctor.addStatement("$N = $T.list($N)", f.java, CHECKS, f.java);
        } else if (raw instanceof ParameterizedTypeName && ((ParameterizedTypeName) raw).rawType().equals(ModelPlanner.MAP)) {
          ctor.addStatement("$N = $T.map($N)", f.java, CHECKS, f.java);
        }
      }
      String value = f.triState ? f.java + ".orElse(null)" : f.java;
      if (f.tagValues != null && f.tagValues.size() > 1) {
        checks.addStatement("checks.oneOf($S, $N, $L)", f.wire, f.java, stringList(f.tagValues));
      }
      constraintChecks(checks, rb, patterns, f.wire, value, f.type, f.constraints);
      if (mentionsModel(f.type)) {
        checks.addStatement("checks.nested($S, $L)", f.wire, value);
      }
      String fieldDoc = fieldDoc(f);
      if (!fieldDoc.isEmpty()) {
        params.add("@param " + f.java + " " + fieldDoc);
      }
    }
    if (d.open) {
      TypeName mapType = ParameterizedTypeName.get(ModelPlanner.MAP, ModelPlanner.STRING, d.openValueType);
      ctor.addParameter(
          ParameterSpec.builder(mapType, "additionalProperties")
              .addAnnotation(JSON_ANY_SETTER)
              .addAnnotation(JSON_ANY_GETTER)
              .build());
      ctor.addStatement("additionalProperties = $T.extras(additionalProperties)", CHECKS);
      params.add("@param additionalProperties properties this client doesn't know, kept as they came");
    }
    rb.recordConstructor(ctor.build());
    String description = Docs.javadoc(d.description);
    String doc = description + (description.isEmpty() || params.isEmpty() ? "" : "\n\n") + String.join("\n", params);
    if (!doc.isEmpty()) {
      rb.addJavadoc("$L\n", doc);
    }
    rb.addMethod(
        MethodSpec.methodBuilder("validate")
            .addAnnotation(Override.class)
            .addModifiers(Modifier.PUBLIC)
            .addParameter(CHECKS, "checks")
            .addCode(checks.build())
            .build());
    builder(rb, d);
    for (Ir.Decl n : d.nested) {
      rb.addType(type(n));
    }
    return rb.build();
  }

  /** {@code public}, and {@code static} for a nested type (JavaPoet asks for it in an interface). */
  static Modifier[] modifiers(ClassName cn) {
    return cn.enclosingClassName() == null
        ? new Modifier[] {Modifier.PUBLIC}
        : new Modifier[] {Modifier.PUBLIC, Modifier.STATIC};
  }

  /** A component's declared type: tri-state, required, or nullable. */
  private TypeName componentType(Ir.Field f) {
    if (f.triState) {
      return ParameterizedTypeName.get(OPTIONAL_NULLABLE, f.type);
    }
    if (f.required && !f.nullable) {
      return f.type;
    }
    return nullable(f.type);
  }

  private static TypeName nullable(TypeName t) {
    if (t instanceof ArrayTypeName) {
      return t;
    }
    return t.annotated(AnnotationSpec.builder(NULLABLE).build());
  }

  private String fieldDoc(Ir.Field f) {
    String text = Docs.javadoc(f.description);
    List<String> notes = new ArrayList<>();
    if (f.required && !f.nullable && f.constValue == null && f.tagValues == null) {
      notes.add("Required.");
    }
    if (f.triState) {
      notes.add("Absent, an explicit {@code null}, or a value.");
    }
    if (f.defaultValue != null) {
      notes.add("Defaults to <code>" + Docs.javadoc(String.valueOf(f.defaultValue)) + "</code> on the server.");
    }
    if (f.constValue != null) {
      notes.add("Always <code>" + Docs.javadoc(String.valueOf(f.constValue)) + "</code>.");
    }
    String joined = String.join(" ", notes);
    if (text.isEmpty()) {
      return joined;
    }
    return joined.isEmpty() ? text : text + (text.endsWith(".") ? " " : ". ") + joined;
  }

  private void builder(TypeSpec.Builder rb, Ir.RecordDecl d) {
    ClassName cn = d.name;
    ClassName bn = cn.nestedClass("Builder");
    TypeSpec.Builder b =
        TypeSpec.classBuilder(bn)
            .addModifiers(Modifier.PUBLIC, Modifier.STATIC, Modifier.FINAL)
            .addJavadoc("Builds a {@link $T}; {@link #build()} checks it against the API's constraints.\n", cn);
    MethodSpec.Builder copy = MethodSpec.constructorBuilder().addModifiers(Modifier.PRIVATE).addParameter(cn, "source");
    List<String> args = new ArrayList<>();
    for (Ir.Field f : d.fields) {
      TypeName ft = componentType(f);
      FieldSpec.Builder field = FieldSpec.builder(ft, f.java, Modifier.PRIVATE);
      if (f.triState) {
        field.initializer("$T.absent()", OPTIONAL_NULLABLE);
      } else if (f.tagValues != null && f.tagValues.size() == 1) {
        field.initializer("$S", f.tagValues.get(0));
      } else if (f.constValue != null) {
        field.initializer("$L", literal(f.constValue));
      } else if (f.required && planner.index.get(f.type) instanceof Ir.EnumDecl
          && ((Ir.EnumDecl) planner.index.get(f.type)).values().size() == 1) {
        // A required enum with one value: the builder starts with it.
        field.initializer("$T.$L", f.type, Names.constant(((Ir.EnumDecl) planner.index.get(f.type)).values().get(0)));
      }
      b.addField(field.build());
      copy.addStatement("this.$N = source.$N", f.java, f.java);
      args.add(f.java);
      boolean fixed = f.constValue != null || (f.tagValues != null && f.tagValues.size() == 1);
      if (fixed) {
        continue;
      }
      String fdoc = fieldDoc(f);
      if (f.triState) {
        b.addMethod(
            setter(bn, f.java, nullable(f.type), fdoc + (fdoc.isEmpty() ? "" : "\n<p>") + "A {@code null} sends an explicit {@code null}.")
                .addStatement("this.$N = $T.of($N)", f.java, OPTIONAL_NULLABLE, f.java)
                .addStatement("return this")
                .build());
      } else {
        b.addMethod(
            setter(bn, f.java, ft, fdoc).addStatement("this.$N = $N", f.java, f.java).addStatement("return this").build());
      }
      Ir.UnionDecl textUnion = textUnion(f.type);
      if (textUnion != null) {
        Ir.Variant text = textUnion.textVariant();
        CodeBlock wrap = CodeBlock.of("new $T($N)", text.type(), f.java);
        b.addMethod(
            setter(bn, f.java, ModelPlanner.STRING, "The text form of {@link #" + f.java + "(" + textUnion.name.simpleName() + ")}.")
                .addStatement(
                    f.triState ? "this.$N = $T.of($L)" : "this.$N = $L",
                    f.triState ? new Object[] {f.java, OPTIONAL_NULLABLE, wrap} : new Object[] {f.java, wrap})
                .addStatement("return this")
                .build());
      }
    }
    if (d.open) {
      TypeName mapType = ParameterizedTypeName.get(ClassName.get(LinkedHashMap.class), ModelPlanner.STRING, d.openValueType);
      b.addField(FieldSpec.builder(mapType, "additionalProperties", Modifier.PRIVATE).initializer("new $T<>()", LinkedHashMap.class).build());
      copy.addStatement("this.additionalProperties.putAll(source.additionalProperties())");
      args.add("additionalProperties");
      b.addMethod(
          MethodSpec.methodBuilder("putAdditionalProperty")
              .addJavadoc("Adds a property beside the known ones.\n")
              .addModifiers(Modifier.PUBLIC)
              .returns(bn)
              .addParameter(ModelPlanner.STRING, "key")
              .addParameter(nullable(d.openValueType), "value")
              .addStatement("this.additionalProperties.put($T.requireNonNull(key, $S), value)", Objects.class, "key")
              .addStatement("return this")
              .build());
    }
    b.addMethod(MethodSpec.constructorBuilder().addModifiers(Modifier.PRIVATE).build());
    b.addMethod(copy.build());
    b.addMethod(
        MethodSpec.methodBuilder("build")
            .addJavadoc("The {@link $T}.\n\n@return the value\n@throws $T when it breaks the API's constraints (every problem is listed)\n", cn, ClassName.get(MODELS, "ValidationException"))
            .addModifiers(Modifier.PUBLIC)
            .returns(cn)
            .addStatement("$T built = new $T($L)", cn, cn, String.join(", ", args))
            .addStatement("built.validate()")
            .addStatement("return built")
            .build());
    rb.addType(b.build());
    rb.addMethod(
        MethodSpec.methodBuilder("builder")
            .addJavadoc("A builder for a {@link $T}.\n\n@return the builder\n", cn)
            .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
            .returns(bn)
            .addStatement("return new $T()", bn)
            .build());
    rb.addMethod(
        MethodSpec.methodBuilder("toBuilder")
            .addJavadoc("A builder that starts from this value.\n\n@return the builder\n")
            .addModifiers(Modifier.PUBLIC)
            .returns(bn)
            .addStatement("return new $T(this)", bn)
            .build());
  }

  private static MethodSpec.Builder setter(ClassName builder, String name, TypeName type, String doc) {
    MethodSpec.Builder m =
        MethodSpec.methodBuilder(name).addModifiers(Modifier.PUBLIC).returns(builder).addParameter(type, name);
    if (!doc.isEmpty()) {
      m.addJavadoc("$L\n", doc);
    }
    return m;
  }

  private Ir.UnionDecl textUnion(TypeName t) {
    if (t instanceof ClassName) {
      Ir.Decl d = planner.index.get(t);
      if (d instanceof Ir.UnionDecl && ((Ir.UnionDecl) d).textVariant() != null) {
        return (Ir.UnionDecl) d;
      }
    }
    return null;
  }

  /** Whether a value of this type can hold a generated model (and so needs a nested check). */
  private boolean mentionsModel(TypeName t) {
    if (t instanceof ParameterizedTypeName) {
      for (TypeName a : ((ParameterizedTypeName) t).typeArguments()) {
        if (mentionsModel(a)) {
          return true;
        }
      }
      return false;
    }
    if (t instanceof ClassName) {
      Ir.Decl d = planner.index.get(t);
      return d instanceof Ir.RecordDecl || d instanceof Ir.UnionDecl;
    }
    return false;
  }

  /** Emits the checks for one value's constraints (strings, numbers, lists, maps, and their items). */
  private void constraintChecks(
      CodeBlock.Builder out, TypeSpec.Builder owner, PatternNames patterns, String name, String value, TypeName type, Ir.Constraints c) {
    constraintChecks(out, owner, patterns, name, value, type, c, 0);
  }

  private void constraintChecks(
      CodeBlock.Builder out, TypeSpec.Builder owner, PatternNames patterns, String name, String value, TypeName type, Ir.Constraints c, int depth) {
    if (c == null || c.isEmpty()) {
      return;
    }
    if (c.minLength() != null) {
      out.addStatement("checks.minLength($S, $L, $L)", name, value, c.minLength());
    }
    if (c.maxLength() != null) {
      out.addStatement("checks.maxLength($S, $L, $L)", name, value, c.maxLength());
    }
    if (c.pattern() != null) {
      try {
        Pattern.compile(c.pattern());
      } catch (RuntimeException e) {
        throw new GenerationException(name + ": pattern " + c.pattern() + " isn't a Java regex: " + e.getMessage());
      }
      String field = patterns.name(c.pattern());
      if (patterns.added.add(field)) {
        owner.addField(
            FieldSpec.builder(Pattern.class, field, Modifier.PRIVATE, Modifier.STATIC, Modifier.FINAL)
                .initializer("$T.compile($S)", Pattern.class, c.pattern())
                .build());
      }
      out.addStatement("checks.pattern($S, $L, $N)", name, value, field);
    }
    if (c.minimum() != null) {
      out.addStatement("checks.minimum($S, $L, $S)", name, value, c.minimum().toPlainString());
    }
    if (c.maximum() != null) {
      out.addStatement("checks.maximum($S, $L, $S)", name, value, c.maximum().toPlainString());
    }
    if (c.exclusiveMinimum() != null) {
      out.addStatement("checks.exclusiveMinimum($S, $L, $S)", name, value, c.exclusiveMinimum().toPlainString());
    }
    if (c.minItems() != null) {
      out.addStatement("checks.minItems($S, $L, $L)", name, value, c.minItems());
    }
    if (c.maxItems() != null) {
      out.addStatement("checks.maxItems($S, $L, $L)", name, value, c.maxItems());
    }
    if (c.uniqueItems()) {
      out.addStatement("checks.uniqueItems($S, $L)", name, value);
    }
    if (c.minProperties() != null) {
      out.addStatement("checks.minProperties($S, $L, $L)", name, value, c.minProperties());
    }
    if (c.maxProperties() != null) {
      out.addStatement("checks.maxProperties($S, $L, $L)", name, value, c.maxProperties());
    }
    TypeName element = typeArgument(type, ModelPlanner.LIST, 0);
    if (c.items() != null && !c.items().isEmpty() && element != null) {
      CodeBlock.Builder inner = CodeBlock.builder();
      String item = "item" + depth;
      constraintChecks(inner, owner, patterns, "", item, element, c.items(), depth + 1);
      out.add("checks.eachItem($S, $L, $L -> {\n$>$L$<});\n", name, value, item, inner.build());
    }
    TypeName mapValue = typeArgument(type, ModelPlanner.MAP, 1);
    if (c.keys() != null && !c.keys().isEmpty() && mapValue != null) {
      CodeBlock.Builder inner = CodeBlock.builder();
      String key = "key" + depth;
      constraintChecks(inner, owner, patterns, "", key, ModelPlanner.STRING, c.keys(), depth + 1);
      out.add("checks.eachKey($S, $L, $L -> {\n$>$L$<});\n", name, value, key, inner.build());
    }
    if (c.values() != null && !c.values().isEmpty() && mapValue != null) {
      CodeBlock.Builder inner = CodeBlock.builder();
      String entry = "entry" + depth;
      constraintChecks(inner, owner, patterns, "", entry, mapValue, c.values(), depth + 1);
      out.add("checks.eachValue($S, $L, $L -> {\n$>$L$<});\n", name, value, entry, inner.build());
    }
  }

  private static TypeName typeArgument(TypeName t, ClassName raw, int index) {
    if (t instanceof ParameterizedTypeName && ((ParameterizedTypeName) t).rawType().equals(raw)) {
      return ((ParameterizedTypeName) t).typeArguments().get(index);
    }
    return null;
  }

  /** Names the compiled patterns of one record. */
  private static final class PatternNames {
    final Map<String, String> byPattern = new LinkedHashMap<>();
    final Set<String> added = new HashSet<>();

    String name(String pattern) {
      return byPattern.computeIfAbsent(pattern, p -> "PATTERN_" + byPattern.size());
    }
  }

  private static String literal(Object v) {
    if (v instanceof String) {
      return CodeBlock.of("$S", v).toString();
    }
    if (v instanceof Integer || v instanceof Long) {
      return v + "L";
    }
    return String.valueOf(v);
  }

  static CodeBlock stringList(List<String> values) {
    CodeBlock.Builder b = CodeBlock.builder().add("$T.of(", List.class);
    for (int i = 0; i < values.size(); i++) {
      b.add(i == 0 ? "$S" : ", $S", values.get(i));
    }
    return b.add(")").build();
  }

  // ---------------------------------------------------------------------------------------------
  // Enums
  // ---------------------------------------------------------------------------------------------

  private TypeSpec enumClass(Ir.EnumDecl d) {
    ClassName cn = d.name();
    ClassName valueEnum = cn.nestedClass(cn.simpleNames().contains("Value") ? "Known" : "Value");
    TypeSpec.Builder tb =
        TypeSpec.classBuilder(cn)
            .addModifiers(Modifier.PUBLIC, Modifier.FINAL)
            .addJavadoc(
                "$L$L\n",
                Docs.javadoc(d.description()).isEmpty() ? "" : Docs.javadoc(d.description()) + "\n\n<p>",
                "One of the values below, or one this client doesn't know yet: {@link #of} keeps any value,"
                    + " and {@link #value()} is {@code UNRECOGNIZED} for an unknown one. Switch on {@link #value()}.");
    TypeSpec.Builder ve =
        TypeSpec.enumBuilder(valueEnum)
            .addModifiers(Modifier.PUBLIC)
            .addJavadoc("The values this client knows, and {@code UNRECOGNIZED}.\n");
    Set<String> constants = new HashSet<>();
    CodeBlock.Builder known = CodeBlock.builder().add("$T.ofEntries(", Map.class);
    int i = 0;
    for (String v : d.values()) {
      String c = Names.constant(v);
      if (c.equals("UNRECOGNIZED") || !constants.add(c)) {
        throw new GenerationException(cn + ": enum value \"" + v + "\" makes a duplicate constant " + c);
      }
      ve.addEnumConstant(c);
      tb.addField(
          FieldSpec.builder(cn, c, Modifier.PUBLIC, Modifier.STATIC, Modifier.FINAL)
              .addJavadoc("<code>$L</code>\n", Docs.javadoc(v))
              .initializer("new $T($S, $T.$L)", cn, v, valueEnum, c)
              .build());
      known.add(i++ == 0 ? "\n$>$T.entry($S, $L)" : ",\n$T.entry($S, $L)", Map.class, v, c);
    }
    known.add("$<)");
    ve.addEnumConstant("UNRECOGNIZED");
    TypeName mapType = ParameterizedTypeName.get(ModelPlanner.MAP, ModelPlanner.STRING, cn);
    tb.addField(FieldSpec.builder(mapType, "byValue", Modifier.PRIVATE, Modifier.STATIC, Modifier.FINAL).initializer(known.build()).build());
    tb.addField(ModelPlanner.STRING, "raw", Modifier.PRIVATE, Modifier.FINAL);
    tb.addField(valueEnum, "value", Modifier.PRIVATE, Modifier.FINAL);
    tb.addMethod(
        MethodSpec.constructorBuilder()
            .addModifiers(Modifier.PRIVATE)
            .addParameter(ModelPlanner.STRING, "raw")
            .addParameter(valueEnum, "value")
            .addStatement("this.raw = raw")
            .addStatement("this.value = value")
            .build());
    tb.addMethod(
        MethodSpec.methodBuilder("of")
            .addJavadoc("The value for this text: a known constant, or an unrecognized value that keeps it.\n")
            .addAnnotation(JSON_CREATOR)
            .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
            .returns(cn)
            .addParameter(ModelPlanner.STRING, "raw")
            .addStatement("$T known = byValue.get($T.requireNonNull(raw, $S))", cn, Objects.class, "raw")
            .addStatement("return known != null ? known : new $T(raw, $T.UNRECOGNIZED)", cn, valueEnum)
            .build());
    tb.addMethod(
        MethodSpec.methodBuilder("asString")
            .addJavadoc("The value as the API spells it.\n")
            .addAnnotation(JSON_VALUE)
            .addModifiers(Modifier.PUBLIC)
            .returns(ModelPlanner.STRING)
            .addStatement("return raw")
            .build());
    tb.addMethod(
        MethodSpec.methodBuilder("value")
            .addJavadoc("Which known value this is, or {@code UNRECOGNIZED}.\n")
            .addModifiers(Modifier.PUBLIC)
            .returns(valueEnum)
            .addStatement("return value")
            .build());
    tb.addMethod(
        MethodSpec.methodBuilder("isKnown")
            .addJavadoc("Whether this client knows the value.\n")
            .addModifiers(Modifier.PUBLIC)
            .returns(TypeName.BOOLEAN)
            .addStatement("return value != $T.UNRECOGNIZED", valueEnum)
            .build());
    tb.addMethod(
        MethodSpec.methodBuilder("equals")
            .addAnnotation(Override.class)
            .addModifiers(Modifier.PUBLIC)
            .returns(TypeName.BOOLEAN)
            .addParameter(Object.class, "other")
            .addStatement("return other instanceof $T && (($T) other).raw.equals(raw)", cn, cn)
            .build());
    tb.addMethod(
        MethodSpec.methodBuilder("hashCode")
            .addAnnotation(Override.class)
            .addModifiers(Modifier.PUBLIC)
            .returns(TypeName.INT)
            .addStatement("return raw.hashCode()")
            .build());
    tb.addMethod(
        MethodSpec.methodBuilder("toString")
            .addAnnotation(Override.class)
            .addModifiers(Modifier.PUBLIC)
            .returns(ModelPlanner.STRING)
            .addStatement("return raw")
            .build());
    if (cn.enclosingClassName() != null) {
      tb.addModifiers(Modifier.STATIC);
    }
    tb.addType(ve.build());
    return tb.build();
  }

  // ---------------------------------------------------------------------------------------------
  // Unions
  // ---------------------------------------------------------------------------------------------

  private TypeSpec union(Ir.UnionDecl u) {
    ClassName cn = u.name;
    TypeSpec.Builder ib = TypeSpec.interfaceBuilder(cn).addModifiers(modifiers(cn)).addModifiers(Modifier.SEALED).addSuperinterface(MODEL);
    StringBuilder doc = new StringBuilder(Docs.javadoc(u.description));
    if (doc.length() > 0) {
      doc.append("\n\n<p>");
    }
    doc.append("One of:\n<ul>\n");
    for (Ir.Variant v : u.variants) {
      doc.append("<li>{@link ").append(String.join(".", v.type().simpleNames())).append("}");
      if (v.tags() != null) {
        doc.append(": {@code ").append(u.tagWire).append("} is ").append(String.join(" or ", v.tags().stream().map(t -> "<code>" + Docs.javadoc(t) + "</code>").toList()));
      } else if (v.text()) {
        doc.append(": text").append(v.allowed() == null ? "" : ", <code>" + Docs.javadoc(String.join("|", v.allowed())) + "</code>");
      } else if (v.uniqueRequired() != null) {
        doc.append(": has {@code ").append(v.uniqueRequired().get(0)).append("}");
      }
      doc.append("</li>\n");
      ib.addPermittedSubclass(v.type());
    }
    if (u.unrecognized != null) {
      doc.append("<li>{@link ").append(u.unrecognized.simpleName()).append("}: a variant this client doesn't know yet, kept as it came</li>\n");
      ib.addPermittedSubclass(u.unrecognized);
    }
    doc.append("</ul>");
    ib.addJavadoc("$L\n", doc.toString());

    boolean tagged = u.kind == Ir.UnionKind.TAGGED;
    if (tagged) {
      ib.addMethod(
          MethodSpec.methodBuilder(u.tagJava)
              .addJavadoc("The {@code $L} that tells the variants apart.\n", u.tagWire)
              .addModifiers(Modifier.PUBLIC, Modifier.ABSTRACT)
              .returns(ModelPlanner.STRING)
              .build());
    }
    if (u.kind == Ir.UnionKind.TAGGED || u.kind == Ir.UnionKind.DEDUCED) {
      AnnotationSpec.Builder info = AnnotationSpec.builder(JSON_TYPE_INFO);
      if (tagged) {
        info.addMember("use", "$T.Id.NAME", JSON_TYPE_INFO)
            .addMember("include", "$T.As.EXISTING_PROPERTY", JSON_TYPE_INFO)
            .addMember("property", "$S", u.tagWire)
            .addMember("visible", "true");
      } else {
        info.addMember("use", "$T.Id.DEDUCTION", JSON_TYPE_INFO);
      }
      info.addMember("defaultImpl", "$T.class", u.unrecognized);
      ib.addAnnotation(info.build());
      AnnotationSpec.Builder subs = AnnotationSpec.builder(JSON_SUB_TYPES);
      for (Ir.Variant v : u.variants) {
        AnnotationSpec.Builder t = AnnotationSpec.builder(JSON_SUB_TYPES.nestedClass("Type")).addMember("value", "$T.class", v.type());
        if (tagged) {
          if (v.tags().size() == 1) {
            t.addMember("name", "$S", v.tags().get(0));
          } else {
            t.addMember("names", "$L", stringArray(v.tags()));
          }
        }
        subs.addMember("value", "$L", t.build());
      }
      ib.addAnnotation(subs.build());
    }
    if (u.unrecognized != null) {
      ib.addType(unrecognized(u));
    }
    if (u.kind == Ir.UnionKind.TEXT_OR_OBJECT) {
      Ir.Variant text = u.textVariant();
      ib.addMethod(
          MethodSpec.methodBuilder("of")
              .addJavadoc("The text variant.\n")
              .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
              .returns(cn)
              .addParameter(ModelPlanner.STRING, "text")
              .addStatement("return new $T(text)", text.type())
              .build());
      if (text.allowed() != null && text.allowed().size() == 1) {
        ib.addField(
            FieldSpec.builder(text.type(), Names.constant(text.allowed().get(0)), Modifier.PUBLIC, Modifier.STATIC, Modifier.FINAL)
                .addJavadoc("<code>$L</code>\n", Docs.javadoc(text.allowed().get(0)))
                .initializer("new $T($S)", text.type(), text.allowed().get(0))
                .build());
      }
      ib.addType(textVariant(u, text));
    }
    for (Ir.Decl n : u.nested) {
      ib.addType(type(n));
    }
    return ib.build();
  }

  private static CodeBlock stringArray(List<String> values) {
    CodeBlock.Builder b = CodeBlock.builder().add("{");
    for (int i = 0; i < values.size(); i++) {
      b.add(i == 0 ? "$S" : ", $S", values.get(i));
    }
    return b.add("}").build();
  }

  private TypeSpec unrecognized(Ir.UnionDecl u) {
    MethodSpec.Builder ctor = MethodSpec.compactConstructorBuilder().addModifiers(Modifier.PUBLIC);
    TypeName props = ParameterizedTypeName.get(ModelPlanner.MAP, ModelPlanner.STRING, ModelPlanner.OBJECT);
    String tag = u.tagWire != null && u.objectKind == Ir.UnionKind.TAGGED ? u.tagWire : null;
    if (tag != null) {
      ctor.addParameter(
          ParameterSpec.builder(nullable(ModelPlanner.STRING), u.tagJava)
              .addAnnotation(AnnotationSpec.builder(JSON_PROPERTY).addMember("value", "$S", tag).build())
              .build());
    }
    ctor.addParameter(ParameterSpec.builder(props, "properties").addAnnotation(JSON_ANY_SETTER).addAnnotation(JSON_ANY_GETTER).build());
    ctor.addStatement("properties = $T.extras(properties)", CHECKS);
    TypeSpec.Builder rb = TypeSpec.recordBuilder(u.unrecognized);
    return rb
        .addModifiers(modifiers(u.unrecognized))
        .addAnnotation(AnnotationSpec.builder(JSON_INCLUDE).addMember("value", "$T.Include.NON_NULL", JSON_INCLUDE).build())
        .addSuperinterface(u.name)
        .addJavadoc(
            "A variant this client doesn't know yet (a newer runtime's), kept as it came.\n\n"
                + (tag != null ? "@param $N its {@code $L}\n" : "$L$L")
                + "@param properties its other properties\n",
            tag != null ? u.tagJava : "",
            tag != null ? tag : "")
        .recordConstructor(ctor.build())
        .addMethod(
            MethodSpec.methodBuilder("validate")
                .addAnnotation(Override.class)
                .addModifiers(Modifier.PUBLIC)
                .addParameter(CHECKS, "checks")
                .addComment("Nothing to check: the client doesn't know this variant's constraints.")
                .build())
        .build();
  }

  private TypeSpec textVariant(Ir.UnionDecl u, Ir.Variant text) {
    MethodSpec ctor =
        MethodSpec.compactConstructorBuilder()
            .addModifiers(Modifier.PUBLIC)
            .addParameter(ParameterSpec.builder(ModelPlanner.STRING, "value").addAnnotation(JSON_VALUE).build())
            .addStatement("$T.requireNonNull(value, $S)", Objects.class, String.join(".", u.name.simpleNames()) + " text")
            .build();
    MethodSpec.Builder validate =
        MethodSpec.methodBuilder("validate")
            .addAnnotation(Override.class)
            .addModifiers(Modifier.PUBLIC)
            .addParameter(CHECKS, "checks");
    if (text.allowed() != null) {
      validate.addStatement("checks.oneOf($S, value, $L)", "", stringList(text.allowed()));
    }
    return TypeSpec.recordBuilder(text.type())
        .addModifiers(modifiers(text.type()))
        .addSuperinterface(u.name)
        .addJavadoc("The text variant.\n\n@param value the text\n")
        .recordConstructor(ctor)
        .addMethod(validate.build())
        .build();
  }
}
